#!/usr/bin/env bash
#
# generate-imports.sh — inventory an existing Ory Network project and emit
# Terraform import blocks for every importable resource it contains.
#
# Usage:
#   export ORY_WORKSPACE_API_KEY=ory_wak_...   # required
#   export ORY_PROJECT_ID=<project-uuid>       # required
#   export ORY_PROJECT_API_KEY=ory_pat_...     # optional: OAuth2 clients, JWKS,
#                                              #   trusted issuers, identity count
#   export ORY_JWKS_SETS=my-set,other-set      # optional: JWKS set IDs to import
#   ./generate-imports.sh > imports.tf
#
# Endpoint overrides (self-explanatory defaults for Ory Network production):
#   ORY_CONSOLE_API_URL   default https://api.console.ory.sh
#   ORY_PROJECT_API_URL   printf template, default https://%s.projects.oryapis.com
#
# Import blocks are written to stdout, progress and warnings to stderr.
# Resources that hold data rather than configuration (identities, relationship
# tuples) and resources whose secrets cannot be recovered (project API keys)
# are emitted as comments with an explanation instead of import blocks.

set -euo pipefail

CONSOLE_URL="${ORY_CONSOLE_API_URL:-https://api.console.ory.sh}"
PROJECT_URL_TEMPLATE="${ORY_PROJECT_API_URL:-https://%s.projects.oryapis.com}"

log() { echo "$*" >&2; }
die() {
  log "ERROR: $*"
  exit 1
}

command -v curl >/dev/null || die "curl is required"
command -v jq >/dev/null || die "jq is required"
[ -n "${ORY_WORKSPACE_API_KEY:-}" ] || die "ORY_WORKSPACE_API_KEY is required"
[ -n "${ORY_PROJECT_ID:-}" ] || die "ORY_PROJECT_ID is required"

# GET from the Ory Console API (workspace API key). Dies on API errors.
console_get() {
  local path="$1" resp
  resp=$(curl -sS -H "Authorization: Bearer $ORY_WORKSPACE_API_KEY" "$CONSOLE_URL$path") ||
    die "GET $path failed (network)"
  if echo "$resp" | jq -e '.error? // empty' >/dev/null 2>&1; then
    die "GET $path: $(echo "$resp" | jq -r '.error.message // .error')"
  fi
  echo "$resp"
}

# GET from the project admin API (project API key). Prints nothing on error so
# optional sections can degrade gracefully.
admin_get() {
  local path="$1" resp
  resp=$(curl -sS -H "Authorization: Bearer $ORY_PROJECT_API_KEY" "$ADMIN_URL$path") || return 1
  if echo "$resp" | jq -e '.error? // empty' >/dev/null 2>&1; then
    log "WARN: GET $path: $(echo "$resp" | jq -r '.error.message // .error')"
    return 1
  fi
  echo "$resp"
}

# Turn an arbitrary string into a valid Terraform resource label fragment.
sanitize() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | sed -e 's/[^a-z0-9]\{1,\}/_/g' -e 's/^_//' -e 's/_$//' |
    sed -e 's/^$/x/' -e 's/^\([0-9]\)/x\1/'
}

short_id() { echo "$1" | cut -c1-8; }

emit() {
  printf 'import {\n  to = %s\n  id = "%s"\n}\n\n' "$1" "$2"
}

log "Inventorying project $ORY_PROJECT_ID ..."
PROJECT_JSON=$(console_get "/projects/$ORY_PROJECT_ID")
PROJECT_NAME=$(echo "$PROJECT_JSON" | jq -r '.name')
PROJECT_SLUG=$(echo "$PROJECT_JSON" | jq -r '.slug')
WORKSPACE_ID=$(echo "$PROJECT_JSON" | jq -r '.workspace_id // empty')
# shellcheck disable=SC2059 # PROJECT_URL_TEMPLATE is intentionally a printf template
ADMIN_URL=$(printf "$PROJECT_URL_TEMPLATE" "$PROJECT_SLUG")

cat <<EOF
# Terraform import blocks for Ory Network project:
#   name: $PROJECT_NAME
#   id:   $ORY_PROJECT_ID
#   slug: $PROJECT_SLUG
#
# Generated by generate-imports.sh. Review before use: remove blocks for
# resources you do not want Terraform to manage, then run
#   terraform plan -generate-config-out=generated.tf
# to generate matching resource configuration.

EOF

# --- Project and project config (always present) -----------------------------
emit "ory_project.main" "$ORY_PROJECT_ID"
emit "ory_project_config.main" "$ORY_PROJECT_ID"

if [ -n "$WORKSPACE_ID" ]; then
  cat <<EOF
# The project belongs to workspace $WORKSPACE_ID. Uncomment to also manage the
# workspace itself (name only; deleting the resource deletes the workspace).
# import {
#   to = ory_workspace.main
#   id = "$WORKSPACE_ID"
# }

EOF
fi

# --- Custom domains -----------------------------------------------------------
DOMAINS=$(console_get "/projects/$ORY_PROJECT_ID/cname" | jq -c '. // []')
echo "$DOMAINS" | jq -c '.[]' | while read -r row; do
  id=$(echo "$row" | jq -r '.id')
  hostname=$(echo "$row" | jq -r '.hostname')
  emit "ory_custom_domain.$(sanitize "$hostname")" "$ORY_PROJECT_ID/$id"
done
log "custom domains: $(echo "$DOMAINS" | jq 'length')"

# --- Event streams ------------------------------------------------------------
STREAMS=$(console_get "/projects/$ORY_PROJECT_ID/eventstreams" | jq -c '.event_streams // []')
echo "$STREAMS" | jq -c '.[]' | while read -r row; do
  id=$(echo "$row" | jq -r '.id')
  type=$(echo "$row" | jq -r '.type // "stream"')
  emit "ory_event_stream.$(sanitize "$type")_$(short_id "$id")" "$ORY_PROJECT_ID/$id"
done
log "event streams: $(echo "$STREAMS" | jq 'length')"

# --- Organizations (B2B) --------------------------------------------------------
ORGS_RESP=$(console_get "/projects/$ORY_PROJECT_ID/organizations")
if [ "$(echo "$ORGS_RESP" | jq -r '.has_next_page // false')" = "true" ]; then
  log "WARN: organization list is paginated and only the first page was fetched"
fi
ORGS=$(echo "$ORGS_RESP" | jq -c '.organizations // []')
echo "$ORGS" | jq -c '.[]' | while read -r row; do
  id=$(echo "$row" | jq -r '.id')
  label=$(echo "$row" | jq -r '.label')
  emit "ory_organization.$(sanitize "$label")_$(short_id "$id")" "$ORY_PROJECT_ID/$id"
done
log "organizations: $(echo "$ORGS" | jq 'length')"

# --- Project API keys (comment only: key values are unrecoverable) -------------
KEYS=$(console_get "/projects/$ORY_PROJECT_ID/tokens" | jq -c '. // []')
if [ "$(echo "$KEYS" | jq 'length')" -gt 0 ]; then
  echo "# Project API keys exist but are not imported by default: the secret value"
  echo "# is only returned at creation time and cannot be recovered by an import."
  echo "# Uncomment to import one anyway (state will hold a null value):"
  echo "$KEYS" | jq -c '.[]' | while read -r row; do
    id=$(echo "$row" | jq -r '.id')
    name=$(echo "$row" | jq -r '.name // "key"')
    printf '# import {\n#   to = ory_project_api_key.%s\n#   id = "%s"\n# }\n' \
      "$(sanitize "$name")_$(short_id "$id")" "$ORY_PROJECT_ID/$id"
  done
  echo
fi
log "project API keys: $(echo "$KEYS" | jq 'length') (commented out)"

# --- Social sign-in providers (from the project revision) ----------------------
SOCIAL=$(echo "$PROJECT_JSON" | jq -c '[.services.identity.config.selfservice.methods.oidc.config.providers[]?]')
if [ "$(echo "$SOCIAL" | jq 'length')" -gt 0 ]; then
  echo "# Social provider client secrets are never returned by the API. After"
  echo "# generating config, re-supply each client_secret (or client_secret_wo)."
fi
echo "$SOCIAL" | jq -c '.[]' | while read -r row; do
  id=$(echo "$row" | jq -r '.id')
  emit "ory_social_provider.$(sanitize "$id")" "$id"
done
log "social providers: $(echo "$SOCIAL" | jq 'length')"

# --- SAML providers (from the project revision) ---------------------------------
SAML=$(echo "$PROJECT_JSON" | jq -c '[.services.identity.config.selfservice.methods.saml.config.providers[]?]')
echo "$SAML" | jq -c '.[]' | while read -r row; do
  id=$(echo "$row" | jq -r '.id')
  emit "ory_saml_provider.$(sanitize "$id")" "$id"
done
log "saml providers: $(echo "$SAML" | jq 'length')"

# --- Actions / webhooks (from the project revision) -----------------------------
# after-timing hooks nested under an auth method: flow:after:<method>:METHOD:url
# after-timing hooks in a flat array (recovery/verification): auth method
# placeholder "_" (the provider ignores it for those flows).
# before-timing hooks: flow:before:METHOD:url
ACTIONS=$(echo "$PROJECT_JSON" | jq -c '
  .services.identity.config.selfservice.flows // {} | to_entries
  | map(.key as $flow
      | (.value.before.hooks // [] | map(select(.hook == "web_hook")
          | {label: "\($flow)_before", id: "\($flow):before:\(.config.method // "POST"):\(.config.url)"})),
        (.value.after // {} | to_entries
          | map(.key as $m
              | if .key == "hooks" then
                  (.value | map(select(.hook == "web_hook")
                    | {label: "\($flow)_after", id: "\($flow):after:_:\(.config.method // "POST"):\(.config.url)"}))
                else
                  (.value.hooks // [] | map(select(.hook == "web_hook")
                    | {label: "\($flow)_after_\($m)", id: "\($flow):after:\($m):\(.config.method // "POST"):\(.config.url)"}))
                end)
          | add // [])
    )
  | add // []')
n=0
echo "$ACTIONS" | jq -c '.[]' | while read -r row; do
  n=$((n + 1))
  label=$(echo "$row" | jq -r '.label')
  id=$(echo "$row" | jq -r '.id')
  emit "ory_action.$(sanitize "$label")_$n" "$ORY_PROJECT_ID:$id"
done
log "actions (web_hooks): $(echo "$ACTIONS" | jq 'length')"

# --- Email templates (from the project revision) --------------------------------
# Only templates with actual content (subject or body) are customized; the rest
# are empty skeletons for the defaults and cannot be imported meaningfully.
TEMPLATES=$(echo "$PROJECT_JSON" | jq -c '
  [.services.identity.config.courier.templates // {} | to_entries[]
   | .key as $base | .value | to_entries[]
   | select(.key == "valid" or .key == "invalid")
   | .key as $validity | .value.email // {}
   | select((.subject // "") != "" or (.body.html // "") != "" or (.body.plaintext // "") != "")
   | "\($base)_\($validity)"]')
echo "$TEMPLATES" | jq -r '.[]' | while read -r type; do
  emit "ory_email_template.$(sanitize "$type")" "$type"
done
log "email templates with custom content: $(echo "$TEMPLATES" | jq 'length')"

# --- Identity schemas: not importable, list them for reference -------------------
SCHEMAS=$(echo "$PROJECT_JSON" | jq -c '[.services.identity.config.identity.schemas[]?.id | select(startswith("preset://") | not)]')
if [ "$(echo "$SCHEMAS" | jq 'length')" -gt 0 ]; then
  echo "# Identity schemas are immutable and intentionally NOT importable."
  echo "# Existing schemas stay as they are; manage future schemas with new"
  echo "# ory_identity_schema resources, or read these with the ory_identity_schema"
  echo "# data source:"
  echo "$SCHEMAS" | jq -r '.[] | "#   schema id: \(.)"'
  echo
fi
log "identity schemas (not importable): $(echo "$SCHEMAS" | jq 'length')"

# --- Keto namespaces / relationships ---------------------------------------------
NAMESPACES=$(echo "$PROJECT_JSON" | jq -c '[.services.permission.config.namespaces[]?.name]')
if [ "$(echo "$NAMESPACES" | jq 'length')" -gt 0 ]; then
  echo "# Keto namespaces (managed inside ory_project_config, not separate resources):"
  echo "$NAMESPACES" | jq -r '.[] | "#   \(.)"'
  echo "# Relationship tuples are data, not configuration; import selectively with an"
  echo "# import block whose id is \"namespace:object#relation@subject\". List tuples"
  echo "# via GET /relation-tuples?namespace=<name> on the project API."
  echo
fi
log "keto namespaces: $(echo "$NAMESPACES" | jq 'length')"

# --- Project-API-key gated resources ---------------------------------------------
if [ -n "${ORY_PROJECT_API_KEY:-}" ]; then
  # OAuth2 clients
  if CLIENTS=$(admin_get "/admin/clients?page_size=500"); then
    COUNT=$(echo "$CLIENTS" | jq 'length')
    [ "$COUNT" = "500" ] && log "WARN: 500 OAuth2 clients returned; results may be truncated (pagination not followed)"
    if [ "$COUNT" -gt 0 ]; then
      echo "# OAuth2 client secrets are only returned at creation time. After"
      echo "# generating config, re-supply client_secret (or client_secret_wo) for"
      echo "# confidential clients. For clients registered via dynamic client"
      echo "# registration, use ory_oidc_dynamic_client instead of ory_oauth2_client."
    fi
    echo "$CLIENTS" | jq -c '.[]' | while read -r row; do
      id=$(echo "$row" | jq -r '.client_id')
      name=$(echo "$row" | jq -r '.client_name // ""')
      emit "ory_oauth2_client.$(sanitize "${name:-client}")_$(short_id "$id")" "$id"
    done
    log "oauth2 clients: $COUNT"
  fi

  # Trusted OAuth2 JWT grant issuers
  if ISSUERS=$(admin_get "/admin/trust/grants/jwt-bearer/issuers"); then
    echo "$ISSUERS" | jq -c '.[]?' | while read -r row; do
      id=$(echo "$row" | jq -r '.id')
      issuer=$(echo "$row" | jq -r '.issuer')
      emit "ory_trusted_oauth2_jwt_grant_issuer.$(sanitize "$issuer")_$(short_id "$id")" "$id"
    done
    log "trusted jwt grant issuers: $(echo "$ISSUERS" | jq 'length')"
  fi

  # JSON web key sets: there is no list-all endpoint, so sets must be named
  # explicitly. Default hydra.* sets are system-managed; do not import them.
  if [ -n "${ORY_JWKS_SETS:-}" ]; then
    echo "# JWKS imports put PRIVATE keys into the Terraform state. Handle with care."
    IFS=',' read -r -a SETS <<<"$ORY_JWKS_SETS"
    for set in "${SETS[@]}"; do
      set=$(echo "$set" | sed -e 's/^ *//' -e 's/ *$//')
      [ -z "$set" ] && continue
      if admin_get "/admin/keys/$set" >/dev/null; then
        emit "ory_json_web_key_set.$(sanitize "$set")" "$ORY_PROJECT_ID/$set"
      else
        log "WARN: JWKS set '$set' not found, skipping"
      fi
    done
  else
    log "jwks: set ORY_JWKS_SETS=set1,set2 to import custom key sets (no list endpoint exists)"
  fi

  # Identities: data, not configuration. Report the count only (first page).
  if IDENTITIES=$(admin_get "/admin/identities?page_size=250"); then
    IDENTITY_COUNT=$(echo "$IDENTITIES" | jq 'length')
    SUFFIX=""
    if [ "$IDENTITY_COUNT" -gt 0 ]; then
      [ "$IDENTITY_COUNT" = "250" ] && SUFFIX="+"
      echo "# This project has $IDENTITY_COUNT$SUFFIX identities. Identities are data, not"
      echo "# configuration; import selectively (e.g. service accounts) with an import"
      echo "# block whose id is the identity UUID. Credentials are not importable."
      echo
    fi
    log "identities: $IDENTITY_COUNT$SUFFIX (not imported)"
  fi
else
  log "ORY_PROJECT_API_KEY not set: skipping OAuth2 clients, trusted JWT issuers, JWKS, identities"
fi

log "Done. Review the emitted blocks, then run: terraform plan -generate-config-out=generated.tf"
