// Code generated by go generate; DO NOT EDIT.
// Source: internal/codegen/cmd/generate/main.go
// Mappings: internal/codegen/mappings.yaml

package projectconfig

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// StringPatchEntry maps a string field to its JSON Patch path.
type StringPatchEntry struct {
	Field *types.String
	Path  string
}

// BoolPatchEntry maps a bool field to its JSON Patch path.
type BoolPatchEntry struct {
	Field *types.Bool
	Path  string
}

// Int64PatchEntry maps an int64 field to its JSON Patch path.
type Int64PatchEntry struct {
	Field *types.Int64
	Path  string
}

// ListStringPatchEntry maps a list(string) field to its JSON Patch path.
type ListStringPatchEntry struct {
	Field *types.List
	Path  string
}

// MapStringPatchEntry maps a map(string) field to its JSON Patch path.
type MapStringPatchEntry struct {
	Field *types.Map
	Path  string
}

// simpleStringPatchEntries returns all simple string attribute patch mappings.
func simpleStringPatchEntries(plan *ProjectConfigResourceModel) []StringPatchEntry {
	return []StringPatchEntry{
		{&plan.SessionLifespan, "/services/identity/config/session/lifespan"},
		{&plan.SessionCookieSameSite, "/services/identity/config/session/cookie/same_site"},
		{&plan.SessionWhoamiRequiredAAL, "/services/identity/config/session/whoami/required_aal"},
		{&plan.OAuth2AccessTokenLifespan, "/services/oauth2/config/ttl/access_token"},
		{&plan.OAuth2RefreshTokenLifespan, "/services/oauth2/config/ttl/refresh_token"},
		{&plan.OAuth2AuthCodeLifespan, "/services/oauth2/config/ttl/auth_code"},
		{&plan.OAuth2IDTokenLifespan, "/services/oauth2/config/ttl/id_token"},
		{&plan.OAuth2LoginConsentRequestLifespan, "/services/oauth2/config/ttl/login_consent_request"},
		{&plan.OAuth2AccessTokenStrategy, "/services/oauth2/config/strategies/access_token"},
		{&plan.OAuth2JWTScopeClaim, "/services/oauth2/config/strategies/jwt/scope_claim"},
		{&plan.OAuth2ScopeStrategy, "/services/oauth2/config/strategies/scope"},
		{&plan.OAuth2ConsentURL, "/services/oauth2/config/urls/consent"},
		{&plan.OAuth2LoginURL, "/services/oauth2/config/urls/login"},
		{&plan.OAuth2LogoutURL, "/services/oauth2/config/urls/logout"},
		{&plan.OAuth2ErrorURL, "/services/oauth2/config/urls/error"},
		{&plan.OAuth2IssuerURL, "/services/oauth2/config/urls/self/issuer"},
		{&plan.OAuth2CookiesSameSiteMode, "/services/oauth2/config/serve/cookies/same_site_mode"},
		{&plan.LoginUIURL, "/services/identity/config/selfservice/flows/login/ui_url"},
		{&plan.RegistrationUIURL, "/services/identity/config/selfservice/flows/registration/ui_url"},
		{&plan.RecoveryUIURL, "/services/identity/config/selfservice/flows/recovery/ui_url"},
		{&plan.VerificationUIURL, "/services/identity/config/selfservice/flows/verification/ui_url"},
		{&plan.SettingsUIURL, "/services/identity/config/selfservice/flows/settings/ui_url"},
		{&plan.ErrorUIURL, "/services/identity/config/selfservice/flows/error/ui_url"},
		{&plan.CodeLifespan, "/services/identity/config/selfservice/methods/code/config/lifespan"},
		{&plan.LoginStyle, "/services/identity/config/selfservice/flows/login/style"},
		{&plan.SettingsLifespan, "/services/identity/config/selfservice/flows/settings/lifespan"},
		{&plan.SettingsPrivilegedSessionMaxAge, "/services/identity/config/selfservice/flows/settings/privileged_session_max_age"},
		{&plan.RequiredAAL, "/services/identity/config/selfservice/flows/settings/required_aal"},
		{&plan.VerificationUse, "/services/identity/config/selfservice/flows/verification/use"},
		{&plan.VerificationLifespan, "/services/identity/config/selfservice/flows/verification/lifespan"},
		{&plan.SMTPFromAddress, "/services/identity/config/courier/smtp/from_address"},
		{&plan.SMTPFromName, "/services/identity/config/courier/smtp/from_name"},
		{&plan.TOTPIssuer, "/services/identity/config/selfservice/methods/totp/config/issuer"},
		{&plan.WebAuthnRPDisplayName, "/services/identity/config/selfservice/methods/webauthn/config/rp/display_name"},
		{&plan.WebAuthnRPID, "/services/identity/config/selfservice/methods/webauthn/config/rp/id"},
		{&plan.CourierDeliveryStrategy, "/services/identity/config/courier/delivery_strategy"},
		{&plan.AccountExperienceFaviconURL, "/services/account_experience/config/favicon_url"},
		{&plan.AccountExperienceLogoURL, "/services/account_experience/config/logo_url"},
		{&plan.AccountExperienceName, "/services/account_experience/config/name"},
		{&plan.AccountExperienceStylesheet, "/services/account_experience/config/stylesheet"},
		{&plan.AccountExperienceLocale, "/services/account_experience/config/default_locale"},
		{&plan.OAuth2GrantJWTMaxTTL, "/services/oauth2/config/oauth2/grant/jwt/max_ttl"},
		{&plan.OAuth2GrantRefreshTokenRotationGracePeriod, "/services/oauth2/config/oauth2/grant/refresh_token_rotation_grace_period"},
		{&plan.OAuth2RefreshTokenHook, "/services/oauth2/config/oauth2/refresh_token_hook"},
		{&plan.OAuth2TokenHook, "/services/oauth2/config/oauth2/token_hook/url"},
		{&plan.OIDCSubjectIdentifiersPairwiseSalt, "/services/oauth2/config/oidc/subject_identifiers/pairwise_salt"},
		{&plan.OAuth2UrlsPostLogoutRedirect, "/services/oauth2/config/urls/post_logout_redirect"},
		{&plan.OAuth2UrlsRegistration, "/services/oauth2/config/urls/registration"},
		{&plan.OAuth2WebfingerOIDCDiscoveryAuthURL, "/services/oauth2/config/webfinger/oidc/discovery/auth_url"},
		{&plan.OAuth2WebfingerOIDCDiscoveryClientRegistrationURL, "/services/oauth2/config/webfinger/oidc/discovery/client_registration_url"},
		{&plan.OAuth2WebfingerOIDCDiscoveryJwksURL, "/services/oauth2/config/webfinger/oidc/discovery/jwks_url"},
		{&plan.OAuth2WebfingerOIDCDiscoveryTokenURL, "/services/oauth2/config/webfinger/oidc/discovery/token_url"},
		{&plan.OAuth2WebfingerOIDCDiscoveryUserinfoURL, "/services/oauth2/config/webfinger/oidc/discovery/userinfo_url"},
		{&plan.CookiesSameSite, "/services/identity/config/cookies/same_site"},
		{&plan.CourierHTTPRequestConfigAuthAPIKeyIn, "/services/identity/config/courier/http/auth/config/in"},
		{&plan.CourierHTTPRequestConfigAuthAPIKeyName, "/services/identity/config/courier/http/auth/config/name"},
		{&plan.CourierHTTPRequestConfigAuthAPIKeyValue, "/services/identity/config/courier/http/auth/config/value"},
		{&plan.CourierHTTPRequestConfigAuthBasicAuthPassword, "/services/identity/config/courier/http/auth/config/password"},
		{&plan.CourierHTTPRequestConfigAuthBasicAuthUser, "/services/identity/config/courier/http/auth/config/user"},
		{&plan.CourierHTTPRequestConfigBody, "/services/identity/config/courier/http/body"},
		{&plan.CourierHTTPRequestConfigURL, "/services/identity/config/courier/http/url"},
		{&plan.CourierSMTPLocalName, "/services/identity/config/courier/smtp/local_name"},
		{&plan.CourierTemplatesLoginCodeValidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/login_code/valid/email/body/html"},
		{&plan.CourierTemplatesLoginCodeValidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/login_code/valid/email/body/plaintext"},
		{&plan.CourierTemplatesLoginCodeValidEmailSubject, "/services/identity/config/courier/smtp/templates/login_code/valid/email/subject"},
		{&plan.CourierTemplatesLoginCodeValidSMSBodyPlaintext, "/services/identity/config/courier/smtp/templates/login_code/valid/sms/plaintext"},
		{&plan.CourierTemplatesRecoveryCodeInvalidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/recovery_code/invalid/email/body/html"},
		{&plan.CourierTemplatesRecoveryCodeInvalidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/recovery_code/invalid/email/body/plaintext"},
		{&plan.CourierTemplatesRecoveryCodeInvalidEmailSubject, "/services/identity/config/courier/smtp/templates/recovery_code/invalid/email/subject"},
		{&plan.CourierTemplatesRecoveryCodeValidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/recovery_code/valid/email/body/html"},
		{&plan.CourierTemplatesRecoveryCodeValidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/recovery_code/valid/email/body/plaintext"},
		{&plan.CourierTemplatesRecoveryCodeValidEmailSubject, "/services/identity/config/courier/smtp/templates/recovery_code/valid/email/subject"},
		{&plan.CourierTemplatesRecoveryInvalidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/recovery/invalid/email/body/html"},
		{&plan.CourierTemplatesRecoveryInvalidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/recovery/invalid/email/body/plaintext"},
		{&plan.CourierTemplatesRecoveryInvalidEmailSubject, "/services/identity/config/courier/smtp/templates/recovery/invalid/email/subject"},
		{&plan.CourierTemplatesRecoveryValidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/recovery/valid/email/body/html"},
		{&plan.CourierTemplatesRecoveryValidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/recovery/valid/email/body/plaintext"},
		{&plan.CourierTemplatesRecoveryValidEmailSubject, "/services/identity/config/courier/smtp/templates/recovery/valid/email/subject"},
		{&plan.CourierTemplatesRegistrationCodeValidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/registration_code/valid/email/body/html"},
		{&plan.CourierTemplatesRegistrationCodeValidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/registration_code/valid/email/body/plaintext"},
		{&plan.CourierTemplatesRegistrationCodeValidEmailSubject, "/services/identity/config/courier/smtp/templates/registration_code/valid/email/subject"},
		{&plan.CourierTemplatesRegistrationCodeValidSMSBodyPlaintext, "/services/identity/config/courier/smtp/templates/registration_code/valid/sms/body/plaintext"},
		{&plan.CourierTemplatesVerificationCodeInvalidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/verification_code/invalid/email/body/html"},
		{&plan.CourierTemplatesVerificationCodeInvalidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/verification_code/invalid/email/body/plaintext"},
		{&plan.CourierTemplatesVerificationCodeInvalidEmailSubject, "/services/identity/config/courier/smtp/templates/verification_code/invalid/email/subject"},
		{&plan.CourierTemplatesVerificationCodeValidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/verification_code/valid/email/body/html"},
		{&plan.CourierTemplatesVerificationCodeValidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/verification_code/valid/email/body/plaintext"},
		{&plan.CourierTemplatesVerificationCodeValidEmailSubject, "/services/identity/config/courier/smtp/templates/verification_code/valid/email/subject"},
		{&plan.CourierTemplatesVerificationCodeValidSMSBodyPlaintext, "/services/identity/config/courier/smtp/templates/verification_code/valid/sms/body/plaintext"},
		{&plan.CourierTemplatesVerificationInvalidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/verification/invalid/email/body/html"},
		{&plan.CourierTemplatesVerificationInvalidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/verification/invalid/email/body/plaintext"},
		{&plan.CourierTemplatesVerificationInvalidEmailSubject, "/services/identity/config/courier/smtp/templates/verification/invalid/email/subject"},
		{&plan.CourierTemplatesVerificationValidEmailBodyHTML, "/services/identity/config/courier/smtp/templates/verification/valid/email/body/html"},
		{&plan.CourierTemplatesVerificationValidEmailBodyPlaintext, "/services/identity/config/courier/smtp/templates/verification/valid/email/body/plaintext"},
		{&plan.CourierTemplatesVerificationValidEmailSubject, "/services/identity/config/courier/smtp/templates/verification/valid/email/subject"},
		{&plan.FeatureFlagsCacheableSessionsMaxAge, "/services/identity/config/feature_flags/cacheable_sessions_max_age"},
		{&plan.OAuth2ProviderURL, "/services/identity/config/oauth2_provider/url"},
		{&plan.SelfserviceDefaultBrowserReturnURL, "/services/identity/config/selfservice/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterCodeDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/code/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/login/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterLookupSecretDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/lookup_secret/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterOIDCDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/login/after/oidc/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterPasskeyDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/login/after/passkey/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterPasswordDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/login/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterTOTPDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/totp/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterWebAuthnDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/login/after/webauthn/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginLifespan, "/services/identity/config/selfservice/flows/login/lifespan"},
		{&plan.SelfserviceFlowsLogoutAfterDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/logout/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsRecoveryAfterDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/recovery/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsRecoveryLifespan, "/services/identity/config/selfservice/flows/recovery/lifespan"},
		{&plan.SelfserviceFlowsRecoveryUse, "/services/identity/config/selfservice/flows/recovery/use"},
		{&plan.SelfserviceFlowsRegistrationAfterCodeDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/registration/after/code/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/registration/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterOIDCDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/registration/after/oidc/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterPasskeyDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/registration/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterPasswordDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/registration/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterWebAuthnDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/registration/after/webauthn/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationLifespan, "/services/identity/config/selfservice/flows/registration/lifespan"},
		{&plan.SelfserviceFlowsSettingsAfterDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/settings/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterLookupSecretDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/settings/after/lookup_secret/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterOIDCDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/settings/after/oidc/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterPasskeyDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/settings/after/passkey/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterPasswordDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/settings/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterProfileDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/settings/after/profile/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterTOTPDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/settings/after/totp/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterWebAuthnDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/settings/after/webauthn/default_browser_return_url"},
		{&plan.SelfserviceFlowsVerificationAfterDefaultBrowserReturnURL, "/services/identity/config/selfservice/flows/verification/after/default_browser_return_url"},
		{&plan.SelfserviceMethodsLinkConfigBaseURL, "/services/identity/config/selfservice/methods/link/config/base_url"},
		{&plan.SelfserviceMethodsLinkConfigLifespan, "/services/identity/config/selfservice/methods/link/config/lifespan"},
		{&plan.SelfserviceMethodsOIDCConfigBaseRedirectURI, "/services/identity/config/selfservice/methods/oidc/config/base_redirect_uri"},
		{&plan.SelfserviceMethodsPasskeyConfigRPDisplayName, "/services/identity/config/selfservice/methods/passkey/config/rp/display_name"},
		{&plan.SelfserviceMethodsPasskeyConfigRPID, "/services/identity/config/selfservice/methods/passkey/config/rp/id"},
		{&plan.SelfserviceMethodsWebAuthnConfigRPIcon, "/services/identity/config/selfservice/methods/webauthn/config/rp/icon"},
		{&plan.AccountExperienceFaviconDark, "/services/account_experience/config/favicon_dark"},
		{&plan.AccountExperienceFaviconLight, "/services/account_experience/config/favicon_light"},
		{&plan.AccountExperienceLocaleBehavior, "/services/account_experience/config/locale_behavior"},
		{&plan.AccountExperienceLogoDark, "/services/account_experience/config/logo_dark"},
		{&plan.AccountExperienceLogoLight, "/services/account_experience/config/logo_light"},
		{&plan.AccountExperienceThemeVariablesDark, "/services/account_experience/config/theme_variables_dark"},
		{&plan.AccountExperienceThemeVariablesLight, "/services/account_experience/config/theme_variables_light"},
		{&plan.KetoNamespaceConfiguration, "/services/permission/config/namespace_configuration"},
		{&plan.PreviewDefaultReadConsistencyLevel, "/services/identity/config/preview/default_read_consistency_level"},
		{&plan.SelfserviceMethodsCaptchaConfigCFTurnstileBYOSecret, "/services/identity/config/selfservice/methods/captcha/config/cf_turnstile_byo_secret"},
		{&plan.SelfserviceMethodsCaptchaConfigCFTurnstileBYOSitekey, "/services/identity/config/selfservice/methods/captcha/config/cf_turnstile_byo_sitekey"},
		{&plan.SelfserviceMethodsCaptchaConfigCFTurnstileSecret, "/services/identity/config/selfservice/methods/captcha/config/cf_turnstile_secret"},
		{&plan.SelfserviceMethodsCaptchaConfigCFTurnstileSitekey, "/services/identity/config/selfservice/methods/captcha/config/cf_turnstile_sitekey"},
	}
}

// simpleBoolPatchEntries returns all simple bool attribute patch mappings.
func simpleBoolPatchEntries(plan *ProjectConfigResourceModel) []BoolPatchEntry {
	return []BoolPatchEntry{
		{&plan.SessionCookiePersistent, "/services/identity/config/session/cookie/persistent"},
		{&plan.OAuth2MirrorTopLevelClaims, "/services/oauth2/config/oauth2/mirror_top_level_claims"},
		{&plan.OAuth2PKCEEnforced, "/services/oauth2/config/oauth2/pkce/enforced"},
		{&plan.OAuth2PKCEEnforcedForPublicClients, "/services/oauth2/config/oauth2/pkce/enforced_for_public_clients"},
		{&plan.OAuth2SessionEncryptAtRest, "/services/oauth2/config/oauth2/session/encrypt_at_rest"},
		{&plan.OAuth2CookiesSameSiteLegacyWorkaround, "/services/oauth2/config/serve/cookies/same_site_legacy_workaround"},
		{&plan.EnablePassword, "/services/identity/config/selfservice/methods/password/enabled"},
		{&plan.EnableCode, "/services/identity/config/selfservice/methods/code/enabled"},
		{&plan.CodeMFAEnabled, "/services/identity/config/selfservice/methods/code/mfa_enabled"},
		{&plan.EnableOIDC, "/services/identity/config/selfservice/methods/oidc/enabled"},
		{&plan.EnableOIDCAutoLinkPolicy, "/services/identity/config/selfservice/methods/oidc/enable_auto_link_policy"},
		{&plan.EnableTOTP, "/services/identity/config/selfservice/methods/totp/enabled"},
		{&plan.EnableWebAuthn, "/services/identity/config/selfservice/methods/webauthn/enabled"},
		{&plan.EnablePasskey, "/services/identity/config/selfservice/methods/passkey/enabled"},
		{&plan.EnableLookupSecret, "/services/identity/config/selfservice/methods/lookup_secret/enabled"},
		{&plan.EnableProfile, "/services/identity/config/selfservice/methods/profile/enabled"},
		{&plan.CodeMissingCredentialFallbackEnabled, "/services/identity/config/selfservice/methods/code/config/missing_credential_fallback_enabled"},
		{&plan.PasswordCheckHaveIBeenPwned, "/services/identity/config/selfservice/methods/password/config/haveibeenpwned_enabled"},
		{&plan.PasswordIdentifierSimilarity, "/services/identity/config/selfservice/methods/password/config/identifier_similarity_check_enabled"},
		{&plan.EnableRecovery, "/services/identity/config/selfservice/flows/recovery/enabled"},
		{&plan.EnableVerification, "/services/identity/config/selfservice/flows/verification/enabled"},
		{&plan.EnableRegistration, "/services/identity/config/selfservice/flows/registration/enabled"},
		{&plan.VerificationNotifyUnknownRecipients, "/services/identity/config/selfservice/flows/verification/notify_unknown_recipients"},
		{&plan.WebAuthnPasswordless, "/services/identity/config/selfservice/methods/webauthn/config/passwordless"},
		{&plan.OAuth2ClientCredentialsDefaultGrantAllowedScope, "/services/oauth2/config/oauth2/client_credentials/default_grant_allowed_scope"},
		{&plan.OAuth2ExcludeNotBeforeClaim, "/services/oauth2/config/oauth2/exclude_not_before_claim"},
		{&plan.OAuth2GrantJWTIATOptional, "/services/oauth2/config/oauth2/grant/jwt/iat_optional"},
		{&plan.OAuth2GrantJWTJTIOptional, "/services/oauth2/config/oauth2/grant/jwt/jti_optional"},
		{&plan.OIDCDynamicClientRegistrationEnabled, "/services/oauth2/config/oidc/dynamic_client_registration/enabled"},
		{&plan.FeatureFlagsCacheableSessions, "/services/identity/config/feature_flags/cacheable_sessions"},
		{&plan.FeatureFlagsChooseRecoveryAddress, "/services/identity/config/feature_flags/choose_recovery_address"},
		{&plan.FeatureFlagsFasterSessionExtend, "/services/identity/config/feature_flags/faster_session_extend"},
		{&plan.FeatureFlagsLegacyContinueWithVerificationUI, "/services/identity/config/feature_flags/legacy_continue_with_verification_ui"},
		{&plan.FeatureFlagsLegacyOIDCRegistrationNodeGroup, "/services/identity/config/feature_flags/legacy_oidc_registration_node_group"},
		{&plan.FeatureFlagsLegacyRequireVerifiedLoginError, "/services/identity/config/feature_flags/legacy_require_verified_login_error"},
		{&plan.FeatureFlagsUseContinueWithTransitions, "/services/identity/config/feature_flags/use_continue_with_transitions"},
		{&plan.SelfserviceFlowsRecoveryNotifyUnknownRecipients, "/services/identity/config/selfservice/flows/recovery/notify_unknown_recipients"},
		{&plan.SelfserviceFlowsRegistrationEnableLegacyOneStep, "/services/identity/config/selfservice/flows/registration/enable_legacy_one_step"},
		{&plan.SelfserviceFlowsRegistrationLoginHints, "/services/identity/config/selfservice/flows/registration/login_hints"},
		{&plan.SelfserviceMethodsCodePasswordlessEnabled, "/services/identity/config/selfservice/methods/code/passwordless_enabled"},
		{&plan.SelfserviceMethodsCodePasswordlessLoginFallbackEnabled, "/services/identity/config/selfservice/methods/code/passwordless_login_fallback_enabled"},
		{&plan.SelfserviceMethodsLinkEnabled, "/services/identity/config/selfservice/methods/link/enabled"},
		{&plan.SelfserviceMethodsPasswordConfigIgnoreNetworkErrors, "/services/identity/config/selfservice/methods/password/config/ignore_network_errors"},
		{&plan.SelfserviceMethodsSAMLEnabled, "/services/identity/config/selfservice/methods/saml/enabled"},
		{&plan.DisableAccountExperienceWelcomeScreen, "/services/account_experience/config/disable_welcome_screen"},
		{&plan.EnableAXV2, "/services/account_experience/config/enable_ax_v2"},
		{&plan.FeatureFlagsPasswordProfileRegistrationNodeGroup, "/services/identity/config/feature_flags/password_profile_registration_node_group"},
		{&plan.OAuth2ProviderOverrideReturnTo, "/services/identity/config/oauth2_provider/override_return_to"},
		{&plan.SecurityAccountEnumerationMitigate, "/services/identity/config/security/account_enumeration/mitigate"},
		{&plan.SelfserviceMethodsCaptchaConfigBYO, "/services/identity/config/selfservice/methods/captcha/config/byo"},
		{&plan.SelfserviceMethodsCaptchaConfigLegacyInjectNode, "/services/identity/config/selfservice/methods/captcha/config/legacy_inject_node"},
		{&plan.SelfserviceMethodsCaptchaEnabled, "/services/identity/config/selfservice/methods/captcha/enabled"},
	}
}

// simpleInt64PatchEntries returns all simple int64 attribute patch mappings.
func simpleInt64PatchEntries(plan *ProjectConfigResourceModel) []Int64PatchEntry {
	return []Int64PatchEntry{
		{&plan.PasswordMinLength, "/services/identity/config/selfservice/methods/password/config/min_password_length"},
		{&plan.PasswordMaxBreaches, "/services/identity/config/selfservice/methods/password/config/max_breaches"},
		{&plan.SelfserviceMethodsCodeConfigMaxSubmissions, "/services/identity/config/selfservice/methods/code/config/max_submissions"},
	}
}

// simpleListStringPatchEntries returns all simple list(string) attribute patch mappings.
func simpleListStringPatchEntries(plan *ProjectConfigResourceModel) []ListStringPatchEntry {
	return []ListStringPatchEntry{
		{&plan.AccountExperienceEnabledLocales, "/services/account_experience/config/enabled_locales"},
		{&plan.OIDCDynamicClientRegistrationDefaultScope, "/services/oauth2/config/oidc/dynamic_client_registration/default_scope"},
		{&plan.OIDCSubjectIdentifiersSupportedTypes, "/services/oauth2/config/oidc/subject_identifiers/supported_types"},
		{&plan.OAuth2SecretsCookie, "/services/oauth2/config/secrets/cookie"},
		{&plan.OAuth2SecretsPagination, "/services/oauth2/config/secrets/pagination"},
		{&plan.OAuth2SecretsSystem, "/services/oauth2/config/secrets/system"},
		{&plan.OAuth2WebfingerJWKSBroadcastKeys, "/services/oauth2/config/webfinger/jwks/broadcast_keys"},
		{&plan.OAuth2WebfingerOIDCDiscoverySupportedClaims, "/services/oauth2/config/webfinger/oidc/discovery/supported_claims"},
		{&plan.OAuth2WebfingerOIDCDiscoverySupportedScope, "/services/oauth2/config/webfinger/oidc/discovery/supported_scope"},
		{&plan.KetoSecretsPagination, "/services/permission/config/secrets/pagination"},
		{&plan.IdentitySecretsCipher, "/services/identity/config/secrets/cipher"},
		{&plan.IdentitySecretsCookie, "/services/identity/config/secrets/cookie"},
		{&plan.IdentitySecretsDefault, "/services/identity/config/secrets/default"},
		{&plan.IdentitySecretsPagination, "/services/identity/config/secrets/pagination"},
		{&plan.SelfserviceMethodsCaptchaConfigAllowedDomains, "/services/identity/config/selfservice/methods/captcha/config/allowed_domains"},
		{&plan.SelfserviceMethodsPasskeyConfigRPOrigins, "/services/identity/config/selfservice/methods/passkey/config/rp/origins"},
	}
}

// simpleMapStringPatchEntries returns all simple map(string) attribute patch mappings.
func simpleMapStringPatchEntries(plan *ProjectConfigResourceModel) []MapStringPatchEntry {
	return []MapStringPatchEntry{
		{&plan.OAuth2ProviderHeaders, "/services/identity/config/oauth2_provider/headers"},
	}
}
