// Code generated by go generate; DO NOT EDIT.
// Source: internal/codegen/cmd/generate/main.go
// Mappings: internal/codegen/mappings.yaml

package projectconfig

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// StringPatchEntry maps a string field to its JSON Patch path.
type StringPatchEntry struct {
	Field      *types.String
	Deprecated *types.String // fallback when Field is null (deprecated alias)
	Path       string
}

// BoolPatchEntry maps a bool field to its JSON Patch path.
type BoolPatchEntry struct {
	Field      *types.Bool
	Deprecated *types.Bool // fallback when Field is null (deprecated alias)
	Path       string
}

// Int64PatchEntry maps an int64 field to its JSON Patch path.
type Int64PatchEntry struct {
	Field      *types.Int64
	Deprecated *types.Int64 // fallback when Field is null (deprecated alias)
	Path       string
}

// ListStringPatchEntry maps a list(string) field to its JSON Patch path.
type ListStringPatchEntry struct {
	Field      *types.List
	Deprecated *types.List // fallback when Field is null (deprecated alias)
	Path       string
}

// MapStringPatchEntry maps a map(string) field to its JSON Patch path.
type MapStringPatchEntry struct {
	Field      *types.Map
	Deprecated *types.Map // fallback when Field is null (deprecated alias)
	Path       string
}

// simpleStringPatchEntries returns all simple string attribute patch mappings.
func simpleStringPatchEntries(plan *ProjectConfigResourceModel) []StringPatchEntry {
	return []StringPatchEntry{
		{&plan.SessionLifespan, nil, "/services/identity/config/session/lifespan"},
		{&plan.SessionCookieSameSite, nil, "/services/identity/config/session/cookie/same_site"},
		{&plan.SessionWhoamiRequiredAAL, nil, "/services/identity/config/session/whoami/required_aal"},
		{&plan.OAuth2TTLAccessToken, &plan.OAuth2AccessTokenLifespan, "/services/oauth2/config/ttl/access_token"},
		{&plan.OAuth2TTLRefreshToken, &plan.OAuth2RefreshTokenLifespan, "/services/oauth2/config/ttl/refresh_token"},
		{&plan.OAuth2TTLAuthCode, &plan.OAuth2AuthCodeLifespan, "/services/oauth2/config/ttl/auth_code"},
		{&plan.OAuth2TTLIDToken, &plan.OAuth2IDTokenLifespan, "/services/oauth2/config/ttl/id_token"},
		{&plan.OAuth2TTLLoginConsentRequest, &plan.OAuth2LoginConsentRequestLifespan, "/services/oauth2/config/ttl/login_consent_request"},
		{&plan.OAuth2StrategiesAccessToken, &plan.OAuth2AccessTokenStrategy, "/services/oauth2/config/strategies/access_token"},
		{&plan.OAuth2StrategiesJWTScopeClaim, &plan.OAuth2JWTScopeClaim, "/services/oauth2/config/strategies/jwt/scope_claim"},
		{&plan.OAuth2StrategiesScope, &plan.OAuth2ScopeStrategy, "/services/oauth2/config/strategies/scope"},
		{&plan.OAuth2URLsConsent, &plan.OAuth2ConsentURL, "/services/oauth2/config/urls/consent"},
		{&plan.OAuth2URLsLogin, &plan.OAuth2LoginURL, "/services/oauth2/config/urls/login"},
		{&plan.OAuth2URLsLogout, &plan.OAuth2LogoutURL, "/services/oauth2/config/urls/logout"},
		{&plan.OAuth2URLsError, &plan.OAuth2ErrorURL, "/services/oauth2/config/urls/error"},
		{&plan.OAuth2URLsSelfIssuer, &plan.OAuth2IssuerURL, "/services/oauth2/config/urls/self/issuer"},
		{&plan.OAuth2ServeCookiesSameSiteMode, &plan.OAuth2CookiesSameSiteMode, "/services/oauth2/config/serve/cookies/same_site_mode"},
		{&plan.SelfserviceFlowsLoginUIURL, &plan.LoginUIURL, "/services/identity/config/selfservice/flows/login/ui_url"},
		{&plan.SelfserviceFlowsRegistrationUIURL, &plan.RegistrationUIURL, "/services/identity/config/selfservice/flows/registration/ui_url"},
		{&plan.SelfserviceFlowsRecoveryUIURL, &plan.RecoveryUIURL, "/services/identity/config/selfservice/flows/recovery/ui_url"},
		{&plan.SelfserviceFlowsVerificationUIURL, &plan.VerificationUIURL, "/services/identity/config/selfservice/flows/verification/ui_url"},
		{&plan.SelfserviceFlowsSettingsUIURL, &plan.SettingsUIURL, "/services/identity/config/selfservice/flows/settings/ui_url"},
		{&plan.SelfserviceFlowsErrorUIURL, &plan.ErrorUIURL, "/services/identity/config/selfservice/flows/error/ui_url"},
		{&plan.SelfserviceMethodsCodeConfigLifespan, &plan.CodeLifespan, "/services/identity/config/selfservice/methods/code/config/lifespan"},
		{&plan.SelfserviceFlowsLoginStyle, &plan.LoginStyle, "/services/identity/config/selfservice/flows/login/style"},
		{&plan.SelfserviceFlowsSettingsLifespan, &plan.SettingsLifespan, "/services/identity/config/selfservice/flows/settings/lifespan"},
		{&plan.SelfserviceFlowsSettingsPrivilegedSessionMaxAge, &plan.SettingsPrivilegedSessionMaxAge, "/services/identity/config/selfservice/flows/settings/privileged_session_max_age"},
		{&plan.SelfserviceFlowsSettingsRequiredAAL, &plan.RequiredAAL, "/services/identity/config/selfservice/flows/settings/required_aal"},
		{&plan.SelfserviceFlowsVerificationUse, &plan.VerificationUse, "/services/identity/config/selfservice/flows/verification/use"},
		{&plan.SelfserviceFlowsVerificationLifespan, &plan.VerificationLifespan, "/services/identity/config/selfservice/flows/verification/lifespan"},
		{&plan.CourierSMTPFromAddress, &plan.SMTPFromAddress, "/services/identity/config/courier/smtp/from_address"},
		{&plan.CourierSMTPFromName, &plan.SMTPFromName, "/services/identity/config/courier/smtp/from_name"},
		{&plan.SelfserviceMethodsTOTPConfigIssuer, &plan.TOTPIssuer, "/services/identity/config/selfservice/methods/totp/config/issuer"},
		{&plan.SelfserviceMethodsWebAuthnConfigRPDisplayName, &plan.WebAuthnRPDisplayName, "/services/identity/config/selfservice/methods/webauthn/config/rp/display_name"},
		{&plan.SelfserviceMethodsWebAuthnConfigRPID, &plan.WebAuthnRPID, "/services/identity/config/selfservice/methods/webauthn/config/rp/id"},
		{&plan.CourierDeliveryStrategy, nil, "/services/identity/config/courier/delivery_strategy"},
		{&plan.AccountExperienceFaviconURL, nil, "/services/account_experience/config/favicon_url"},
		{&plan.AccountExperienceLogoURL, nil, "/services/account_experience/config/logo_url"},
		{&plan.AccountExperienceName, nil, "/services/account_experience/config/name"},
		{&plan.AccountExperienceStylesheet, nil, "/services/account_experience/config/stylesheet"},
		{&plan.AccountExperienceLocale, nil, "/services/account_experience/config/default_locale"},
		{&plan.OAuth2GrantJWTMaxTTL, nil, "/services/oauth2/config/oauth2/grant/jwt/max_ttl"},
		{&plan.OAuth2GrantRefreshTokenRotationGracePeriod, nil, "/services/oauth2/config/oauth2/grant/refresh_token_rotation_grace_period"},
		{&plan.OAuth2RefreshTokenHook, nil, "/services/oauth2/config/oauth2/refresh_token_hook"},
		{&plan.OAuth2TokenHook, nil, "/services/oauth2/config/oauth2/token_hook/url"},
		{&plan.OIDCSubjectIdentifiersPairwiseSalt, nil, "/services/oauth2/config/oidc/subject_identifiers/pairwise_salt"},
		{&plan.OAuth2UrlsPostLogoutRedirect, nil, "/services/oauth2/config/urls/post_logout_redirect"},
		{&plan.OAuth2UrlsRegistration, nil, "/services/oauth2/config/urls/registration"},
		{&plan.OAuth2WebfingerOIDCDiscoveryAuthURL, nil, "/services/oauth2/config/webfinger/oidc_discovery/auth_url"},
		{&plan.OAuth2WebfingerOIDCDiscoveryClientRegistrationURL, nil, "/services/oauth2/config/webfinger/oidc_discovery/client_registration_url"},
		{&plan.OAuth2WebfingerOIDCDiscoveryJwksURL, nil, "/services/oauth2/config/webfinger/oidc_discovery/jwks_url"},
		{&plan.OAuth2WebfingerOIDCDiscoveryTokenURL, nil, "/services/oauth2/config/webfinger/oidc_discovery/token_url"},
		{&plan.OAuth2WebfingerOIDCDiscoveryUserinfoURL, nil, "/services/oauth2/config/webfinger/oidc_discovery/userinfo_url"},
		{&plan.CookiesSameSite, nil, "/services/identity/config/cookies/same_site"},
		{&plan.CourierHTTPRequestConfigAuthAPIKeyIn, nil, "/services/identity/config/courier/http/request_config/auth/config/in"},
		{&plan.CourierHTTPRequestConfigAuthAPIKeyName, nil, "/services/identity/config/courier/http/request_config/auth/config/name"},
		{&plan.CourierHTTPRequestConfigAuthAPIKeyValue, nil, "/services/identity/config/courier/http/request_config/auth/config/value"},
		{&plan.CourierHTTPRequestConfigAuthBasicAuthPassword, nil, "/services/identity/config/courier/http/request_config/auth/config/password"},
		{&plan.CourierHTTPRequestConfigAuthBasicAuthUser, nil, "/services/identity/config/courier/http/request_config/auth/config/user"},
		{&plan.CourierHTTPRequestConfigBody, nil, "/services/identity/config/courier/http/request_config/body"},
		{&plan.CourierHTTPRequestConfigURL, nil, "/services/identity/config/courier/http/request_config/url"},
		{&plan.CourierSMTPLocalName, nil, "/services/identity/config/courier/smtp/local_name"},
		{&plan.CourierTemplatesLoginCodeValidEmailBodyHTML, nil, "/services/identity/config/courier/templates/login_code/valid/email/body/html"},
		{&plan.CourierTemplatesLoginCodeValidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/login_code/valid/email/body/plaintext"},
		{&plan.CourierTemplatesLoginCodeValidEmailSubject, nil, "/services/identity/config/courier/templates/login_code/valid/email/subject"},
		{&plan.CourierTemplatesLoginCodeValidSMSBodyPlaintext, nil, "/services/identity/config/courier/templates/login_code/valid/sms/body/plaintext"},
		{&plan.CourierTemplatesRecoveryCodeInvalidEmailBodyHTML, nil, "/services/identity/config/courier/templates/recovery_code/invalid/email/body/html"},
		{&plan.CourierTemplatesRecoveryCodeInvalidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/recovery_code/invalid/email/body/plaintext"},
		{&plan.CourierTemplatesRecoveryCodeInvalidEmailSubject, nil, "/services/identity/config/courier/templates/recovery_code/invalid/email/subject"},
		{&plan.CourierTemplatesRecoveryCodeValidEmailBodyHTML, nil, "/services/identity/config/courier/templates/recovery_code/valid/email/body/html"},
		{&plan.CourierTemplatesRecoveryCodeValidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/recovery_code/valid/email/body/plaintext"},
		{&plan.CourierTemplatesRecoveryCodeValidEmailSubject, nil, "/services/identity/config/courier/templates/recovery_code/valid/email/subject"},
		{&plan.CourierTemplatesRecoveryInvalidEmailBodyHTML, nil, "/services/identity/config/courier/templates/recovery/invalid/email/body/html"},
		{&plan.CourierTemplatesRecoveryInvalidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/recovery/invalid/email/body/plaintext"},
		{&plan.CourierTemplatesRecoveryInvalidEmailSubject, nil, "/services/identity/config/courier/templates/recovery/invalid/email/subject"},
		{&plan.CourierTemplatesRecoveryValidEmailBodyHTML, nil, "/services/identity/config/courier/templates/recovery/valid/email/body/html"},
		{&plan.CourierTemplatesRecoveryValidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/recovery/valid/email/body/plaintext"},
		{&plan.CourierTemplatesRecoveryValidEmailSubject, nil, "/services/identity/config/courier/templates/recovery/valid/email/subject"},
		{&plan.CourierTemplatesRegistrationCodeValidEmailBodyHTML, nil, "/services/identity/config/courier/templates/registration_code/valid/email/body/html"},
		{&plan.CourierTemplatesRegistrationCodeValidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/registration_code/valid/email/body/plaintext"},
		{&plan.CourierTemplatesRegistrationCodeValidEmailSubject, nil, "/services/identity/config/courier/templates/registration_code/valid/email/subject"},
		{&plan.CourierTemplatesRegistrationCodeValidSMSBodyPlaintext, nil, "/services/identity/config/courier/templates/registration_code/valid/sms/body/plaintext"},
		{&plan.CourierTemplatesVerificationCodeInvalidEmailBodyHTML, nil, "/services/identity/config/courier/templates/verification_code/invalid/email/body/html"},
		{&plan.CourierTemplatesVerificationCodeInvalidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/verification_code/invalid/email/body/plaintext"},
		{&plan.CourierTemplatesVerificationCodeInvalidEmailSubject, nil, "/services/identity/config/courier/templates/verification_code/invalid/email/subject"},
		{&plan.CourierTemplatesVerificationCodeValidEmailBodyHTML, nil, "/services/identity/config/courier/templates/verification_code/valid/email/body/html"},
		{&plan.CourierTemplatesVerificationCodeValidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/verification_code/valid/email/body/plaintext"},
		{&plan.CourierTemplatesVerificationCodeValidEmailSubject, nil, "/services/identity/config/courier/templates/verification_code/valid/email/subject"},
		{&plan.CourierTemplatesVerificationCodeValidSMSBodyPlaintext, nil, "/services/identity/config/courier/templates/verification_code/valid/sms/body/plaintext"},
		{&plan.CourierTemplatesVerificationInvalidEmailBodyHTML, nil, "/services/identity/config/courier/templates/verification/invalid/email/body/html"},
		{&plan.CourierTemplatesVerificationInvalidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/verification/invalid/email/body/plaintext"},
		{&plan.CourierTemplatesVerificationInvalidEmailSubject, nil, "/services/identity/config/courier/templates/verification/invalid/email/subject"},
		{&plan.CourierTemplatesVerificationValidEmailBodyHTML, nil, "/services/identity/config/courier/templates/verification/valid/email/body/html"},
		{&plan.CourierTemplatesVerificationValidEmailBodyPlaintext, nil, "/services/identity/config/courier/templates/verification/valid/email/body/plaintext"},
		{&plan.CourierTemplatesVerificationValidEmailSubject, nil, "/services/identity/config/courier/templates/verification/valid/email/subject"},
		{&plan.FeatureFlagsCacheableSessionsMaxAge, nil, "/services/identity/config/feature_flags/cacheable_sessions_max_age"},
		{&plan.OAuth2ProviderURL, nil, "/services/identity/config/oauth2_provider/url"},
		{&plan.SelfserviceDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterCodeDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/login/after/code/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/login/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterLookupSecretDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/login/after/lookup_secret/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterOIDCDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/login/after/oidc/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterPasskeyDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/login/after/passkey/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterPasswordDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/login/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterTOTPDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/login/after/totp/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginAfterWebAuthnDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/login/after/webauthn/default_browser_return_url"},
		{&plan.SelfserviceFlowsLoginLifespan, nil, "/services/identity/config/selfservice/flows/login/lifespan"},
		{&plan.SelfserviceFlowsLogoutAfterDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/logout/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsRecoveryAfterDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/recovery/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsRecoveryLifespan, nil, "/services/identity/config/selfservice/flows/recovery/lifespan"},
		{&plan.SelfserviceFlowsRecoveryUse, nil, "/services/identity/config/selfservice/flows/recovery/use"},
		{&plan.SelfserviceFlowsRegistrationAfterCodeDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/registration/after/code/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/registration/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterOIDCDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/registration/after/oidc/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterPasskeyDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/registration/after/passkey/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterPasswordDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/registration/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationAfterWebAuthnDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/registration/after/webauthn/default_browser_return_url"},
		{&plan.SelfserviceFlowsRegistrationLifespan, nil, "/services/identity/config/selfservice/flows/registration/lifespan"},
		{&plan.SelfserviceFlowsSettingsAfterDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/settings/after/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterLookupSecretDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/settings/after/lookup_secret/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterOIDCDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/settings/after/oidc/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterPasskeyDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/settings/after/passkey/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterPasswordDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/settings/after/password/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterProfileDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/settings/after/profile/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterTOTPDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/settings/after/totp/default_browser_return_url"},
		{&plan.SelfserviceFlowsSettingsAfterWebAuthnDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/settings/after/webauthn/default_browser_return_url"},
		{&plan.SelfserviceFlowsVerificationAfterDefaultBrowserReturnURL, nil, "/services/identity/config/selfservice/flows/verification/after/default_browser_return_url"},
		{&plan.SelfserviceMethodsLinkConfigBaseURL, nil, "/services/identity/config/selfservice/methods/link/config/base_url"},
		{&plan.SelfserviceMethodsLinkConfigLifespan, nil, "/services/identity/config/selfservice/methods/link/config/lifespan"},
		{&plan.SelfserviceMethodsOIDCConfigBaseRedirectURI, nil, "/services/identity/config/selfservice/methods/oidc/config/base_redirect_uri"},
		{&plan.SelfserviceMethodsPasskeyConfigRPDisplayName, nil, "/services/identity/config/selfservice/methods/passkey/config/rp/display_name"},
		{&plan.SelfserviceMethodsPasskeyConfigRPID, nil, "/services/identity/config/selfservice/methods/passkey/config/rp/id"},
		{&plan.SelfserviceMethodsWebAuthnConfigRPIcon, nil, "/services/identity/config/selfservice/methods/webauthn/config/rp/icon"},
		{&plan.AccountExperienceFaviconDark, nil, "/services/account_experience/config/favicon_dark"},
		{&plan.AccountExperienceFaviconLight, nil, "/services/account_experience/config/favicon_light"},
		{&plan.AccountExperienceLocaleBehavior, nil, "/services/account_experience/config/locale_behavior"},
		{&plan.AccountExperienceLogoDark, nil, "/services/account_experience/config/logo_dark"},
		{&plan.AccountExperienceLogoLight, nil, "/services/account_experience/config/logo_light"},
		{&plan.AccountExperienceThemeVariablesDark, nil, "/services/account_experience/config/theme_variables_dark"},
		{&plan.AccountExperienceThemeVariablesLight, nil, "/services/account_experience/config/theme_variables_light"},
		{&plan.KetoNamespaceConfiguration, nil, "/services/permission/config/namespaces/location"},
		{&plan.PreviewDefaultReadConsistencyLevel, nil, "/services/identity/config/preview/default_read_consistency_level"},
		{&plan.SelfserviceMethodsCaptchaConfigCFTurnstileSecret, nil, "/services/identity/config/selfservice/methods/captcha/config/cf_turnstile/secret"},
		{&plan.SelfserviceMethodsCaptchaConfigCFTurnstileSitekey, nil, "/services/identity/config/selfservice/methods/captcha/config/cf_turnstile/sitekey"},
	}
}

// simpleBoolPatchEntries returns all simple bool attribute patch mappings.
func simpleBoolPatchEntries(plan *ProjectConfigResourceModel) []BoolPatchEntry {
	return []BoolPatchEntry{
		{&plan.SessionCookiePersistent, nil, "/services/identity/config/session/cookie/persistent"},
		{&plan.OAuth2MirrorTopLevelClaims, nil, "/services/oauth2/config/oauth2/mirror_top_level_claims"},
		{&plan.OAuth2PKCEEnforced, nil, "/services/oauth2/config/oauth2/pkce/enforced"},
		{&plan.OAuth2PKCEEnforcedForPublicClients, nil, "/services/oauth2/config/oauth2/pkce/enforced_for_public_clients"},
		{&plan.OAuth2SessionEncryptAtRest, nil, "/services/oauth2/config/oauth2/session/encrypt_at_rest"},
		{&plan.OAuth2ServeCookiesSameSiteLegacyWorkaround, &plan.OAuth2CookiesSameSiteLegacyWorkaround, "/services/oauth2/config/serve/cookies/same_site_legacy_workaround"},
		{&plan.SelfserviceMethodsPasswordEnabled, &plan.EnablePassword, "/services/identity/config/selfservice/methods/password/enabled"},
		{&plan.SelfserviceMethodsCodeEnabled, &plan.EnableCode, "/services/identity/config/selfservice/methods/code/enabled"},
		{&plan.SelfserviceMethodsCodeMFAEnabled, &plan.CodeMFAEnabled, "/services/identity/config/selfservice/methods/code/mfa_enabled"},
		{&plan.SelfserviceMethodsOIDCEnabled, &plan.EnableOIDC, "/services/identity/config/selfservice/methods/oidc/enabled"},
		{&plan.SelfserviceMethodsOIDCEnableAutoLinkPolicy, &plan.EnableOIDCAutoLinkPolicy, "/services/identity/config/selfservice/methods/oidc/enable_auto_link_policy"},
		{&plan.SelfserviceMethodsTOTPEnabled, &plan.EnableTOTP, "/services/identity/config/selfservice/methods/totp/enabled"},
		{&plan.SelfserviceMethodsWebAuthnEnabled, &plan.EnableWebAuthn, "/services/identity/config/selfservice/methods/webauthn/enabled"},
		{&plan.SelfserviceMethodsPasskeyEnabled, &plan.EnablePasskey, "/services/identity/config/selfservice/methods/passkey/enabled"},
		{&plan.SelfserviceMethodsLookupSecretEnabled, &plan.EnableLookupSecret, "/services/identity/config/selfservice/methods/lookup_secret/enabled"},
		{&plan.SelfserviceMethodsProfileEnabled, &plan.EnableProfile, "/services/identity/config/selfservice/methods/profile/enabled"},
		{&plan.SelfserviceMethodsCodeConfigMissingCredentialFallbackEnabled, &plan.CodeMissingCredentialFallbackEnabled, "/services/identity/config/selfservice/methods/code/config/missing_credential_fallback_enabled"},
		{&plan.SelfserviceMethodsPasswordConfigHaveIBeenPwnedEnabled, &plan.PasswordCheckHaveIBeenPwned, "/services/identity/config/selfservice/methods/password/config/haveibeenpwned_enabled"},
		{&plan.SelfserviceMethodsPasswordConfigIdentifierSimilarityCheckEnabled, &plan.PasswordIdentifierSimilarity, "/services/identity/config/selfservice/methods/password/config/identifier_similarity_check_enabled"},
		{&plan.SelfserviceFlowsRecoveryEnabled, &plan.EnableRecovery, "/services/identity/config/selfservice/flows/recovery/enabled"},
		{&plan.SelfserviceFlowsVerificationEnabled, &plan.EnableVerification, "/services/identity/config/selfservice/flows/verification/enabled"},
		{&plan.SelfserviceFlowsRegistrationEnabled, &plan.EnableRegistration, "/services/identity/config/selfservice/flows/registration/enabled"},
		{&plan.SelfserviceFlowsVerificationNotifyUnknownRecipients, &plan.VerificationNotifyUnknownRecipients, "/services/identity/config/selfservice/flows/verification/notify_unknown_recipients"},
		{&plan.SelfserviceMethodsWebAuthnConfigPasswordless, &plan.WebAuthnPasswordless, "/services/identity/config/selfservice/methods/webauthn/config/passwordless"},
		{&plan.OAuth2ClientCredentialsDefaultGrantAllowedScope, nil, "/services/oauth2/config/oauth2/client_credentials/default_grant_allowed_scope"},
		{&plan.OAuth2ExcludeNotBeforeClaim, nil, "/services/oauth2/config/oauth2/exclude_not_before_claim"},
		{&plan.OAuth2GrantJWTIATOptional, nil, "/services/oauth2/config/oauth2/grant/jwt/iat_optional"},
		{&plan.OAuth2GrantJWTJTIOptional, nil, "/services/oauth2/config/oauth2/grant/jwt/jti_optional"},
		{&plan.OIDCDynamicClientRegistrationEnabled, nil, "/services/oauth2/config/oidc/dynamic_client_registration/enabled"},
		{&plan.FeatureFlagsCacheableSessions, nil, "/services/identity/config/feature_flags/cacheable_sessions"},
		{&plan.FeatureFlagsChooseRecoveryAddress, nil, "/services/identity/config/feature_flags/choose_recovery_address"},
		{&plan.FeatureFlagsFasterSessionExtend, nil, "/services/identity/config/feature_flags/faster_session_extend"},
		{&plan.FeatureFlagsLegacyContinueWithVerificationUI, nil, "/services/identity/config/feature_flags/legacy_continue_with_verification_ui"},
		{&plan.FeatureFlagsLegacyOIDCRegistrationNodeGroup, nil, "/services/identity/config/feature_flags/legacy_oidc_registration_node_group"},
		{&plan.FeatureFlagsLegacyRequireVerifiedLoginError, nil, "/services/identity/config/feature_flags/legacy_require_verified_login_error"},
		{&plan.FeatureFlagsUseContinueWithTransitions, nil, "/services/identity/config/feature_flags/use_continue_with_transitions"},
		{&plan.SelfserviceFlowsRecoveryNotifyUnknownRecipients, nil, "/services/identity/config/selfservice/flows/recovery/notify_unknown_recipients"},
		{&plan.SelfserviceFlowsRegistrationEnableLegacyOneStep, nil, "/services/identity/config/selfservice/flows/registration/enable_legacy_one_step"},
		{&plan.SelfserviceFlowsRegistrationLoginHints, nil, "/services/identity/config/selfservice/flows/registration/login_hints"},
		{&plan.SelfserviceMethodsCodePasswordlessEnabled, nil, "/services/identity/config/selfservice/methods/code/passwordless_enabled"},
		{&plan.SelfserviceMethodsCodePasswordlessLoginFallbackEnabled, nil, "/services/identity/config/selfservice/methods/code/passwordless_login_fallback_enabled"},
		{&plan.SelfserviceMethodsLinkEnabled, nil, "/services/identity/config/selfservice/methods/link/enabled"},
		{&plan.SelfserviceMethodsPasswordConfigIgnoreNetworkErrors, nil, "/services/identity/config/selfservice/methods/password/config/ignore_network_errors"},
		{&plan.SelfserviceMethodsSAMLEnabled, nil, "/services/identity/config/selfservice/methods/saml/enabled"},
		{&plan.DisableAccountExperienceWelcomeScreen, nil, "/services/account_experience/config/disable_welcome_screen"},
		{&plan.EnableAXV2, nil, "/services/account_experience/config/enable_ax_v2"},
		{&plan.FeatureFlagsPasswordProfileRegistrationNodeGroup, nil, "/services/identity/config/feature_flags/password_profile_registration_node_group"},
		{&plan.OAuth2ProviderOverrideReturnTo, nil, "/services/identity/config/oauth2_provider/override_return_to"},
		{&plan.SecurityAccountEnumerationMitigate, nil, "/services/identity/config/security/account_enumeration/mitigate"},
		{&plan.SelfserviceMethodsCaptchaConfigBYO, nil, "/services/identity/config/selfservice/methods/captcha/config/byo"},
		{&plan.SelfserviceMethodsCaptchaConfigLegacyInjectNode, nil, "/services/identity/config/selfservice/methods/captcha/config/legacy_inject_node"},
		{&plan.SelfserviceMethodsCaptchaEnabled, nil, "/services/identity/config/selfservice/methods/captcha/enabled"},
	}
}

// simpleInt64PatchEntries returns all simple int64 attribute patch mappings.
func simpleInt64PatchEntries(plan *ProjectConfigResourceModel) []Int64PatchEntry {
	return []Int64PatchEntry{
		{&plan.SelfserviceMethodsPasswordConfigMinPasswordLength, &plan.PasswordMinLength, "/services/identity/config/selfservice/methods/password/config/min_password_length"},
		{&plan.SelfserviceMethodsPasswordConfigMaxBreaches, &plan.PasswordMaxBreaches, "/services/identity/config/selfservice/methods/password/config/max_breaches"},
		{&plan.SelfserviceMethodsCodeConfigMaxSubmissions, nil, "/services/identity/config/selfservice/methods/code/config/max_submissions"},
	}
}

// simpleListStringPatchEntries returns all simple list(string) attribute patch mappings.
func simpleListStringPatchEntries(plan *ProjectConfigResourceModel) []ListStringPatchEntry {
	return []ListStringPatchEntry{
		{&plan.AccountExperienceEnabledLocales, nil, "/services/account_experience/config/enabled_locales"},
		{&plan.OIDCDynamicClientRegistrationDefaultScope, nil, "/services/oauth2/config/oidc/dynamic_client_registration/default_scope"},
		{&plan.OIDCSubjectIdentifiersSupportedTypes, nil, "/services/oauth2/config/oidc/subject_identifiers/supported_types"},
		{&plan.OAuth2SecretsCookie, nil, "/services/oauth2/config/secrets/cookie"},
		{&plan.OAuth2SecretsPagination, nil, "/services/oauth2/config/secrets/pagination"},
		{&plan.OAuth2SecretsSystem, nil, "/services/oauth2/config/secrets/system"},
		{&plan.OAuth2WebfingerJWKSBroadcastKeys, nil, "/services/oauth2/config/webfinger/jwks/broadcast_keys"},
		{&plan.OAuth2WebfingerOIDCDiscoverySupportedClaims, nil, "/services/oauth2/config/webfinger/oidc/discovery/supported_claims"},
		{&plan.OAuth2WebfingerOIDCDiscoverySupportedScope, nil, "/services/oauth2/config/webfinger/oidc/discovery/supported_scope"},
		{&plan.KetoSecretsPagination, nil, "/services/permission/config/secrets/pagination"},
		{&plan.IdentitySecretsCipher, nil, "/services/identity/config/secrets/cipher"},
		{&plan.IdentitySecretsCookie, nil, "/services/identity/config/secrets/cookie"},
		{&plan.IdentitySecretsDefault, nil, "/services/identity/config/secrets/default"},
		{&plan.IdentitySecretsPagination, nil, "/services/identity/config/secrets/pagination"},
		{&plan.SelfserviceMethodsCaptchaConfigAllowedDomains, nil, "/services/identity/config/selfservice/methods/captcha/config/allowed_domains"},
		{&plan.SelfserviceMethodsPasskeyConfigRPOrigins, nil, "/services/identity/config/selfservice/methods/passkey/config/rp/origins"},
	}
}

// simpleMapStringPatchEntries returns all simple map(string) attribute patch mappings.
func simpleMapStringPatchEntries(plan *ProjectConfigResourceModel) []MapStringPatchEntry {
	return []MapStringPatchEntry{
		{&plan.OAuth2ProviderHeaders, nil, "/services/identity/config/oauth2_provider/headers"},
	}
}
