// Code generated by go generate; DO NOT EDIT.
// Source: internal/codegen/cmd/generate/main.go
// Mappings: internal/codegen/mappings.yaml

package projectconfig

import (
	"context"
	"math"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ory "github.com/ory/client-go"
)

// Ensure imports are used.
var (
	_ *ory.Project
	_ context.Context
	_ attr.Value
)

// StringReadEntry maps a string state field to its config read path.
type StringReadEntry struct {
	Field      *types.String
	Deprecated *types.String // fallback: used only when the primary Field is null in state
	Keys       []string
	SkipEmpty  bool
	// PreserveOnMissing keeps the state value when the API omits Keys, instead
	// of nulling it to surface drift. Set for secrets the API never echoes back
	// and for attributes it accepts but never reports, where a null would show a
	// diff on every plan that no apply can settle.
	PreserveOnMissing bool
	// StorageURL marks a field whose content the API uploads to object storage
	// and reports back as an https URL. Read resolves that URL to the value the
	// configuration holds. See resolveStorageURLContent in helpers.go.
	StorageURL bool
}

// BoolReadEntry maps a bool state field to its config read path.
type BoolReadEntry struct {
	Field             *types.Bool
	Deprecated        *types.Bool // fallback: used only when the primary Field is null in state
	Keys              []string
	PreserveOnMissing bool
	Enum              *BoolEnumValues // when set, the key stores a string enum; map it back by comparing to Enum.True
}

// Int64ReadEntry maps an int64 state field to its config read path.
type Int64ReadEntry struct {
	Field             *types.Int64
	Deprecated        *types.Int64 // fallback: used only when the primary Field is null in state
	Keys              []string
	PreserveOnMissing bool
}

// ListStringReadEntry maps a list(string) state field to its config read path.
type ListStringReadEntry struct {
	Field             *types.List
	Deprecated        *types.List // fallback: used only when the primary Field is null in state
	Keys              []string
	PreserveOnMissing bool
}

// MapStringReadEntry maps a map(string) state field to its config read path.
type MapStringReadEntry struct {
	Field             *types.Map
	Deprecated        *types.Map // fallback: used only when the primary Field is null in state
	Keys              []string
	PreserveOnMissing bool
}

// revisionBoolReadEntries returns bool attributes read from the normalized
// project revision (client.GetProjectNormalizedRevision) instead of the
// project document, keyed by their normalized property name. See
// readRevisionProperties in resource.go.
func revisionBoolReadEntries(state *ProjectConfigResourceModel) []BoolReadEntry {
	return []BoolReadEntry{
		{&state.DisableAccountExperienceWelcomeScreen, nil, []string{"disable_account_experience_welcome_screen"}, false, nil},
	}
}

// readSimpleFields reads all simple attributes from the API response into state.
//
// Missing-key semantics: the API prunes empty values (empty string, empty
// list, empty map, integer zero) from stored configs, so a key the response
// omits is indistinguishable from an applied empty value. When state already
// holds the empty value for the type, the omission is exactly what the write
// produced and the value is kept. Any other state value is nulled so genuine
// out-of-band removals still surface as drift.
func readSimpleFields(ctx context.Context, project *ory.Project, state *ProjectConfigResourceModel) {
	if project.Services.AccountExperience != nil {
		accountExperienceConfig := project.Services.AccountExperience.Config
		for _, e := range account_experienceStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedString(accountExperienceConfig, e.Keys...); ok {
					if e.StorageURL {
						v = resolveStorageURLContent(ctx, v, target.ValueString())
					}
					if !e.SkipEmpty || v != "" {
						*target = types.StringValue(v)
					}
				} else if !e.PreserveOnMissing && target.ValueString() != "" {
					*target = types.StringNull()
				}
			}
		}
		for _, e := range account_experienceBoolReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if e.Enum != nil {
					if v, ok := getNestedString(accountExperienceConfig, e.Keys...); ok {
						*target = types.BoolValue(v == e.Enum.True)
					} else if !e.PreserveOnMissing {
						*target = types.BoolNull()
					}
				} else if v, ok := getNestedBool(accountExperienceConfig, e.Keys...); ok {
					*target = types.BoolValue(v)
				} else if !e.PreserveOnMissing {
					*target = types.BoolNull()
				}
			}
		}
		for _, e := range account_experienceListStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(accountExperienceConfig, e.Keys...); v != nil {
					if arr, ok := v.([]interface{}); ok {
						strs := make([]string, 0, len(arr))
						allStrings := true
						for _, item := range arr {
							if s, ok := item.(string); ok {
								strs = append(strs, s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							listVal, diags := types.ListValueFrom(ctx, types.StringType, strs)
							if !diags.HasError() {
								*target = listVal
							}
						}
					}
				} else if !e.PreserveOnMissing && len(target.Elements()) > 0 {
					*target = types.ListNull(types.StringType)
				}
			}
		}
		for _, e := range account_experienceMapStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(accountExperienceConfig, e.Keys...); v != nil {
					if m, ok := v.(map[string]interface{}); ok {
						strMap := make(map[string]attr.Value, len(m))
						allStrings := true
						for k, val := range m {
							if s, ok := val.(string); ok {
								strMap[k] = types.StringValue(s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							mapVal, diags := types.MapValue(types.StringType, strMap)
							if !diags.HasError() {
								*target = mapVal
							}
						}
					}
				} else if !e.PreserveOnMissing && len(target.Elements()) > 0 {
					*target = types.MapNull(types.StringType)
				}
			}
		}
	}
	if project.Services.Identity != nil {
		identityConfig := project.Services.Identity.Config
		for _, e := range identityStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedString(identityConfig, e.Keys...); ok {
					if e.StorageURL {
						v = resolveStorageURLContent(ctx, v, target.ValueString())
					}
					if !e.SkipEmpty || v != "" {
						*target = types.StringValue(v)
					}
				} else if !e.PreserveOnMissing && target.ValueString() != "" {
					*target = types.StringNull()
				}
			}
		}
		for _, e := range identityBoolReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if e.Enum != nil {
					if v, ok := getNestedString(identityConfig, e.Keys...); ok {
						*target = types.BoolValue(v == e.Enum.True)
					} else if !e.PreserveOnMissing {
						*target = types.BoolNull()
					}
				} else if v, ok := getNestedBool(identityConfig, e.Keys...); ok {
					*target = types.BoolValue(v)
				} else if !e.PreserveOnMissing {
					*target = types.BoolNull()
				}
			}
		}
		for _, e := range identityInt64ReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedFloat(identityConfig, e.Keys...); ok {
					if v == math.Trunc(v) {
						*target = types.Int64Value(int64(v))
					}
				} else if !e.PreserveOnMissing && target.ValueInt64() != 0 {
					*target = types.Int64Null()
				}
			}
		}
		for _, e := range identityListStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(identityConfig, e.Keys...); v != nil {
					if arr, ok := v.([]interface{}); ok {
						strs := make([]string, 0, len(arr))
						allStrings := true
						for _, item := range arr {
							if s, ok := item.(string); ok {
								strs = append(strs, s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							listVal, diags := types.ListValueFrom(ctx, types.StringType, strs)
							if !diags.HasError() {
								*target = listVal
							}
						}
					}
				} else if !e.PreserveOnMissing && len(target.Elements()) > 0 {
					*target = types.ListNull(types.StringType)
				}
			}
		}
		for _, e := range identityMapStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(identityConfig, e.Keys...); v != nil {
					if m, ok := v.(map[string]interface{}); ok {
						strMap := make(map[string]attr.Value, len(m))
						allStrings := true
						for k, val := range m {
							if s, ok := val.(string); ok {
								strMap[k] = types.StringValue(s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							mapVal, diags := types.MapValue(types.StringType, strMap)
							if !diags.HasError() {
								*target = mapVal
							}
						}
					}
				} else if !e.PreserveOnMissing && len(target.Elements()) > 0 {
					*target = types.MapNull(types.StringType)
				}
			}
		}
	}
	if project.Services.Oauth2 != nil {
		oauth2Config := project.Services.Oauth2.Config
		for _, e := range oauth2StringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedString(oauth2Config, e.Keys...); ok {
					if e.StorageURL {
						v = resolveStorageURLContent(ctx, v, target.ValueString())
					}
					if !e.SkipEmpty || v != "" {
						*target = types.StringValue(v)
					}
				} else if !e.PreserveOnMissing && target.ValueString() != "" {
					*target = types.StringNull()
				}
			}
		}
		for _, e := range oauth2BoolReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if e.Enum != nil {
					if v, ok := getNestedString(oauth2Config, e.Keys...); ok {
						*target = types.BoolValue(v == e.Enum.True)
					} else if !e.PreserveOnMissing {
						*target = types.BoolNull()
					}
				} else if v, ok := getNestedBool(oauth2Config, e.Keys...); ok {
					*target = types.BoolValue(v)
				} else if !e.PreserveOnMissing {
					*target = types.BoolNull()
				}
			}
		}
		for _, e := range oauth2Int64ReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedFloat(oauth2Config, e.Keys...); ok {
					if v == math.Trunc(v) {
						*target = types.Int64Value(int64(v))
					}
				} else if !e.PreserveOnMissing && target.ValueInt64() != 0 {
					*target = types.Int64Null()
				}
			}
		}
		for _, e := range oauth2ListStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(oauth2Config, e.Keys...); v != nil {
					if arr, ok := v.([]interface{}); ok {
						strs := make([]string, 0, len(arr))
						allStrings := true
						for _, item := range arr {
							if s, ok := item.(string); ok {
								strs = append(strs, s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							listVal, diags := types.ListValueFrom(ctx, types.StringType, strs)
							if !diags.HasError() {
								*target = listVal
							}
						}
					}
				} else if !e.PreserveOnMissing && len(target.Elements()) > 0 {
					*target = types.ListNull(types.StringType)
				}
			}
		}
	}
	if project.Services.Permission != nil {
		permissionConfig := project.Services.Permission.Config
		for _, e := range permissionStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedString(permissionConfig, e.Keys...); ok {
					if e.StorageURL {
						v = resolveStorageURLContent(ctx, v, target.ValueString())
					}
					if !e.SkipEmpty || v != "" {
						*target = types.StringValue(v)
					}
				} else if !e.PreserveOnMissing && target.ValueString() != "" {
					*target = types.StringNull()
				}
			}
		}
		for _, e := range permissionListStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(permissionConfig, e.Keys...); v != nil {
					if arr, ok := v.([]interface{}); ok {
						strs := make([]string, 0, len(arr))
						allStrings := true
						for _, item := range arr {
							if s, ok := item.(string); ok {
								strs = append(strs, s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							listVal, diags := types.ListValueFrom(ctx, types.StringType, strs)
							if !diags.HasError() {
								*target = listVal
							}
						}
					}
				} else if !e.PreserveOnMissing && len(target.Elements()) > 0 {
					*target = types.ListNull(types.StringType)
				}
			}
		}
	}
}

func account_experienceStringReadEntries(state *ProjectConfigResourceModel) []StringReadEntry {
	return []StringReadEntry{
		{&state.AccountExperienceLocale, nil, []string{"default_locale"}, true, true, false},
		{&state.AccountExperienceLocaleBehavior, nil, []string{"locale_behavior"}, true, true, false},
		{&state.AccountExperienceContactURL, nil, []string{"contact_url"}, false, false, false},
		{&state.AccountExperiencePrivacyPolicyURL, nil, []string{"privacy_policy_url"}, false, false, false},
		{&state.AccountExperienceTermsOfServiceURL, nil, []string{"terms_of_service_url"}, false, false, false},
	}
}

func account_experienceBoolReadEntries(state *ProjectConfigResourceModel) []BoolReadEntry {
	return []BoolReadEntry{
		{&state.EnableAXV2, nil, []string{"enabled"}, false, nil},
		{&state.AccountExperienceHideOryBranding, nil, []string{"hide_ory_branding"}, false, nil},
		{&state.AccountExperienceHideRegistrationLink, nil, []string{"hide_registration_link"}, false, nil},
	}
}

func account_experienceListStringReadEntries(state *ProjectConfigResourceModel) []ListStringReadEntry {
	return []ListStringReadEntry{
		{&state.AccountExperienceEnabledLocales, nil, []string{"enabled_locales"}, false},
	}
}

func account_experienceMapStringReadEntries(state *ProjectConfigResourceModel) []MapStringReadEntry {
	return []MapStringReadEntry{
		{&state.AccountExperienceThemeVariablesDark, nil, []string{"theme_variables_dark"}, false},
		{&state.AccountExperienceThemeVariablesLight, nil, []string{"theme_variables_light"}, false},
	}
}

func identityStringReadEntries(state *ProjectConfigResourceModel) []StringReadEntry {
	return []StringReadEntry{
		{&state.SessionLifespan, nil, []string{"session", "lifespan"}, false, false, false},
		{&state.SessionEarliestPossibleExtend, nil, []string{"session", "earliest_possible_extend"}, false, true, false},
		{&state.SessionCookieSameSite, nil, []string{"session", "cookie", "same_site"}, false, false, false},
		{&state.SessionWhoamiRequiredAAL, nil, []string{"session", "whoami", "required_aal"}, false, false, false},
		{&state.SelfserviceFlowsLoginUIURL, &state.LoginUIURL, []string{"selfservice", "flows", "login", "ui_url"}, false, false, false},
		{&state.SelfserviceFlowsRegistrationUIURL, &state.RegistrationUIURL, []string{"selfservice", "flows", "registration", "ui_url"}, false, false, false},
		{&state.SelfserviceFlowsRecoveryUIURL, &state.RecoveryUIURL, []string{"selfservice", "flows", "recovery", "ui_url"}, false, false, false},
		{&state.SelfserviceFlowsVerificationUIURL, &state.VerificationUIURL, []string{"selfservice", "flows", "verification", "ui_url"}, false, false, false},
		{&state.SelfserviceFlowsSettingsUIURL, &state.SettingsUIURL, []string{"selfservice", "flows", "settings", "ui_url"}, false, false, false},
		{&state.SelfserviceFlowsErrorUIURL, &state.ErrorUIURL, []string{"selfservice", "flows", "error", "ui_url"}, false, false, false},
		{&state.SelfserviceMethodsCodeConfigLifespan, &state.CodeLifespan, []string{"selfservice", "methods", "code", "config", "lifespan"}, false, false, false},
		{&state.SelfserviceFlowsLoginStyle, &state.LoginStyle, []string{"selfservice", "flows", "login", "style"}, false, false, false},
		{&state.SelfserviceFlowsSettingsLifespan, &state.SettingsLifespan, []string{"selfservice", "flows", "settings", "lifespan"}, false, false, false},
		{&state.SelfserviceFlowsSettingsPrivilegedSessionMaxAge, &state.SettingsPrivilegedSessionMaxAge, []string{"selfservice", "flows", "settings", "privileged_session_max_age"}, false, false, false},
		{&state.SelfserviceFlowsSettingsRequiredAAL, &state.RequiredAAL, []string{"selfservice", "flows", "settings", "required_aal"}, false, false, false},
		{&state.SelfserviceFlowsVerificationUse, &state.VerificationUse, []string{"selfservice", "flows", "verification", "use"}, false, false, false},
		{&state.SelfserviceFlowsVerificationLifespan, &state.VerificationLifespan, []string{"selfservice", "flows", "verification", "lifespan"}, false, false, false},
		{&state.CourierSMTPFromAddress, &state.SMTPFromAddress, []string{"courier", "smtp", "from_address"}, false, false, false},
		{&state.CourierSMTPFromName, &state.SMTPFromName, []string{"courier", "smtp", "from_name"}, false, false, false},
		{&state.SelfserviceMethodsTOTPConfigIssuer, &state.TOTPIssuer, []string{"selfservice", "methods", "totp", "config", "issuer"}, false, false, false},
		{&state.SelfserviceMethodsWebAuthnConfigRPDisplayName, &state.WebAuthnRPDisplayName, []string{"selfservice", "methods", "webauthn", "config", "rp", "display_name"}, false, false, false},
		{&state.SelfserviceMethodsWebAuthnConfigRPID, &state.WebAuthnRPID, []string{"selfservice", "methods", "webauthn", "config", "rp", "id"}, false, false, false},
		{&state.CourierDeliveryStrategy, nil, []string{"courier", "delivery_strategy"}, false, false, false},
		{&state.CookiesSameSite, nil, []string{"cookies", "same_site"}, false, false, false},
		{&state.CourierHTTPRequestConfigAuthAPIKeyIn, nil, []string{"courier", "http", "request_config", "auth", "config", "in"}, false, false, false},
		{&state.CourierHTTPRequestConfigAuthAPIKeyName, nil, []string{"courier", "http", "request_config", "auth", "config", "name"}, false, false, false},
		{&state.CourierHTTPRequestConfigAuthBasicAuthUser, nil, []string{"courier", "http", "request_config", "auth", "config", "user"}, false, false, false},
		{&state.CourierHTTPRequestConfigBody, nil, []string{"courier", "http", "request_config", "body"}, false, false, true},
		{&state.CourierHTTPRequestConfigURL, nil, []string{"courier", "http", "request_config", "url"}, false, false, false},
		{&state.CourierSMTPLocalName, nil, []string{"courier", "smtp", "local_name"}, false, false, false},
		{&state.FeatureFlagsCacheableSessionsMaxAge, nil, []string{"feature_flags", "cacheable_sessions_max_age"}, false, false, false},
		{&state.OAuth2ProviderURL, nil, []string{"oauth2_provider", "url"}, false, false, false},
		{&state.SelfserviceDefaultBrowserReturnURL, nil, []string{"selfservice", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsLoginAfterCodeDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "code", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsLoginAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsLoginAfterLookupSecretDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "lookup_secret", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsLoginAfterOIDCDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "oidc", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsLoginAfterPasskeyDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "passkey", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsLoginAfterPasswordDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "password", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsLoginAfterTOTPDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "totp", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsLoginAfterWebAuthnDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "webauthn", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsLoginLifespan, nil, []string{"selfservice", "flows", "login", "lifespan"}, false, false, false},
		{&state.SelfserviceFlowsLogoutAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "logout", "after", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsRecoveryAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "recovery", "after", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsRecoveryLifespan, nil, []string{"selfservice", "flows", "recovery", "lifespan"}, false, false, false},
		{&state.SelfserviceFlowsRecoveryUse, nil, []string{"selfservice", "flows", "recovery", "use"}, false, false, false},
		{&state.SelfserviceFlowsRegistrationAfterCodeDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "code", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsRegistrationAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsRegistrationAfterOIDCDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "oidc", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsRegistrationAfterPasskeyDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "passkey", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsRegistrationAfterPasswordDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "password", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsRegistrationAfterWebAuthnDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "webauthn", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsRegistrationLifespan, nil, []string{"selfservice", "flows", "registration", "lifespan"}, false, false, false},
		{&state.SelfserviceFlowsSettingsAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsSettingsAfterLookupSecretDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "lookup_secret", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsSettingsAfterOIDCDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "oidc", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsSettingsAfterPasskeyDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "passkey", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsSettingsAfterPasswordDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "password", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsSettingsAfterProfileDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "profile", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsSettingsAfterTOTPDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "totp", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsSettingsAfterWebAuthnDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "webauthn", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceFlowsVerificationAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "verification", "after", "default_browser_return_url"}, false, false, false},
		{&state.SelfserviceMethodsLinkConfigBaseURL, nil, []string{"selfservice", "methods", "link", "config", "base_url"}, false, false, false},
		{&state.SelfserviceMethodsLinkConfigLifespan, nil, []string{"selfservice", "methods", "link", "config", "lifespan"}, false, false, false},
		{&state.SelfserviceMethodsOIDCConfigBaseRedirectURI, nil, []string{"selfservice", "methods", "oidc", "config", "base_redirect_uri"}, false, false, false},
		{&state.SelfserviceMethodsPasskeyConfigRPDisplayName, nil, []string{"selfservice", "methods", "passkey", "config", "rp", "display_name"}, false, false, false},
		{&state.SelfserviceMethodsPasskeyConfigRPID, nil, []string{"selfservice", "methods", "passkey", "config", "rp", "id"}, false, false, false},
		{&state.SelfserviceMethodsWebAuthnConfigRPIcon, nil, []string{"selfservice", "methods", "webauthn", "config", "rp", "icon"}, false, true, false},
		{&state.PreviewDefaultReadConsistencyLevel, nil, []string{"preview", "default_read_consistency_level"}, false, false, false},
		{&state.SelfserviceMethodsCaptchaConfigCFTurnstileSecret, nil, []string{"selfservice", "methods", "captcha", "config", "cf_turnstile", "secret"}, false, true, false},
		{&state.SelfserviceMethodsCaptchaConfigCFTurnstileSitekey, nil, []string{"selfservice", "methods", "captcha", "config", "cf_turnstile", "sitekey"}, false, false, false},
		{&state.CourierHTTPRequestConfigAuthType, nil, []string{"courier", "http", "request_config", "auth", "type"}, false, false, false},
		{&state.CourierHTTPRequestConfigMethod, nil, []string{"courier", "http", "request_config", "method"}, false, false, false},
	}
}

func identityBoolReadEntries(state *ProjectConfigResourceModel) []BoolReadEntry {
	return []BoolReadEntry{
		{&state.SessionCookiePersistent, nil, []string{"session", "cookie", "persistent"}, false, nil},
		{&state.SelfserviceMethodsPasswordEnabled, &state.EnablePassword, []string{"selfservice", "methods", "password", "enabled"}, false, nil},
		{&state.SelfserviceMethodsCodeEnabled, &state.EnableCode, []string{"selfservice", "methods", "code", "enabled"}, false, nil},
		{&state.SelfserviceMethodsCodeMFAEnabled, &state.CodeMFAEnabled, []string{"selfservice", "methods", "code", "mfa_enabled"}, false, nil},
		{&state.SelfserviceMethodsOIDCEnabled, &state.EnableOIDC, []string{"selfservice", "methods", "oidc", "enabled"}, false, nil},
		{&state.SelfserviceMethodsOIDCEnableAutoLinkPolicy, &state.EnableOIDCAutoLinkPolicy, []string{"selfservice", "methods", "oidc", "enable_auto_link_policy"}, false, nil},
		{&state.SelfserviceMethodsTOTPEnabled, &state.EnableTOTP, []string{"selfservice", "methods", "totp", "enabled"}, false, nil},
		{&state.SelfserviceMethodsWebAuthnEnabled, &state.EnableWebAuthn, []string{"selfservice", "methods", "webauthn", "enabled"}, false, nil},
		{&state.SelfserviceMethodsPasskeyEnabled, &state.EnablePasskey, []string{"selfservice", "methods", "passkey", "enabled"}, false, nil},
		{&state.SelfserviceMethodsLookupSecretEnabled, &state.EnableLookupSecret, []string{"selfservice", "methods", "lookup_secret", "enabled"}, false, nil},
		{&state.SelfserviceMethodsProfileEnabled, &state.EnableProfile, []string{"selfservice", "methods", "profile", "enabled"}, false, nil},
		{&state.SelfserviceMethodsCodeConfigMissingCredentialFallbackEnabled, &state.CodeMissingCredentialFallbackEnabled, []string{"selfservice", "methods", "code", "config", "missing_credential_fallback_enabled"}, false, nil},
		{&state.SelfserviceMethodsPasswordConfigHaveIBeenPwnedEnabled, &state.PasswordCheckHaveIBeenPwned, []string{"selfservice", "methods", "password", "config", "haveibeenpwned_enabled"}, false, nil},
		{&state.SelfserviceMethodsPasswordConfigIdentifierSimilarityCheckEnabled, &state.PasswordIdentifierSimilarity, []string{"selfservice", "methods", "password", "config", "identifier_similarity_check_enabled"}, false, nil},
		{&state.SelfserviceFlowsRecoveryEnabled, &state.EnableRecovery, []string{"selfservice", "flows", "recovery", "enabled"}, false, nil},
		{&state.SelfserviceFlowsVerificationEnabled, &state.EnableVerification, []string{"selfservice", "flows", "verification", "enabled"}, false, nil},
		{&state.SelfserviceFlowsRegistrationEnabled, &state.EnableRegistration, []string{"selfservice", "flows", "registration", "enabled"}, false, nil},
		{&state.SelfserviceFlowsVerificationNotifyUnknownRecipients, &state.VerificationNotifyUnknownRecipients, []string{"selfservice", "flows", "verification", "notify_unknown_recipients"}, false, nil},
		{&state.SelfserviceMethodsWebAuthnConfigPasswordless, &state.WebAuthnPasswordless, []string{"selfservice", "methods", "webauthn", "config", "passwordless"}, false, nil},
		{&state.FeatureFlagsCacheableSessions, nil, []string{"feature_flags", "cacheable_sessions"}, false, nil},
		{&state.FeatureFlagsChooseRecoveryAddress, nil, []string{"feature_flags", "choose_recovery_address"}, false, nil},
		{&state.FeatureFlagsFasterSessionExtend, nil, []string{"feature_flags", "faster_session_extend"}, false, nil},
		{&state.FeatureFlagsLegacyContinueWithVerificationUI, nil, []string{"feature_flags", "legacy_continue_with_verification_ui"}, false, nil},
		{&state.FeatureFlagsLegacyOIDCRegistrationNodeGroup, nil, []string{"feature_flags", "legacy_oidc_registration_node_group"}, false, nil},
		{&state.FeatureFlagsLegacyRequireVerifiedLoginError, nil, []string{"feature_flags", "legacy_require_verified_login_error"}, false, nil},
		{&state.FeatureFlagsUseContinueWithTransitions, nil, []string{"feature_flags", "use_continue_with_transitions"}, false, nil},
		{&state.SelfserviceFlowsRecoveryNotifyUnknownRecipients, nil, []string{"selfservice", "flows", "recovery", "notify_unknown_recipients"}, false, nil},
		{&state.SelfserviceFlowsRegistrationEnableLegacyOneStep, nil, []string{"selfservice", "flows", "registration", "enable_legacy_one_step"}, false, nil},
		{&state.SelfserviceFlowsRegistrationLoginHints, nil, []string{"selfservice", "flows", "registration", "login_hints"}, false, nil},
		{&state.SelfserviceMethodsCodePasswordlessEnabled, nil, []string{"selfservice", "methods", "code", "passwordless_enabled"}, false, nil},
		{&state.SelfserviceMethodsCodePasswordlessLoginFallbackEnabled, nil, []string{"selfservice", "methods", "code", "passwordless_login_fallback_enabled"}, false, nil},
		{&state.SelfserviceMethodsLinkEnabled, nil, []string{"selfservice", "methods", "link", "enabled"}, false, nil},
		{&state.SelfserviceMethodsPasswordConfigIgnoreNetworkErrors, nil, []string{"selfservice", "methods", "password", "config", "ignore_network_errors"}, false, nil},
		{&state.SelfserviceMethodsSAMLEnabled, nil, []string{"selfservice", "methods", "saml", "enabled"}, false, nil},
		{&state.FeatureFlagsPasswordProfileRegistrationNodeGroup, nil, []string{"feature_flags", "password_profile_registration_node_group"}, false, &BoolEnumValues{"password", "default"}},
		{&state.OAuth2ProviderOverrideReturnTo, nil, []string{"oauth2_provider", "override_return_to"}, false, nil},
		{&state.SecurityAccountEnumerationMitigate, nil, []string{"security", "account_enumeration", "mitigate"}, false, nil},
		{&state.SelfserviceMethodsCaptchaConfigBYO, nil, []string{"selfservice", "methods", "captcha", "config", "byo"}, true, nil},
		{&state.SelfserviceMethodsCaptchaConfigLegacyInjectNode, nil, []string{"selfservice", "methods", "captcha", "config", "legacy_inject_node"}, false, nil},
		{&state.SelfserviceMethodsCaptchaEnabled, nil, []string{"selfservice", "methods", "captcha", "enabled"}, false, nil},
		{&state.SelfserviceMethodsDeviceauthnEnabled, nil, []string{"selfservice", "methods", "deviceauthn", "enabled"}, false, nil},
		{&state.SelfserviceMethodsDeviceauthnConfigInsecureAllowRelaxedAttestation, nil, []string{"selfservice", "methods", "deviceauthn", "config", "insecure_allow_relaxed_attestation"}, false, nil},
		{&state.FeatureFlagsRefreshLoginChooseAddress, nil, []string{"feature_flags", "refresh_login_choose_address"}, false, nil},
		{&state.SelfserviceMethodsDeviceauthnConfigFirstFactor, nil, []string{"selfservice", "methods", "deviceauthn", "config", "first_factor"}, false, nil},
		{&state.SelfserviceMethodsDeviceauthnConfigIosBiometricFirstFactor, nil, []string{"selfservice", "methods", "deviceauthn", "config", "ios_biometric_first_factor"}, false, nil},
	}
}

func identityInt64ReadEntries(state *ProjectConfigResourceModel) []Int64ReadEntry {
	return []Int64ReadEntry{
		{&state.SelfserviceMethodsPasswordConfigMinPasswordLength, &state.PasswordMinLength, []string{"selfservice", "methods", "password", "config", "min_password_length"}, false},
		{&state.SelfserviceMethodsPasswordConfigMaxBreaches, &state.PasswordMaxBreaches, []string{"selfservice", "methods", "password", "config", "max_breaches"}, false},
		{&state.SelfserviceMethodsCodeConfigMaxSubmissions, nil, []string{"selfservice", "methods", "code", "config", "max_submissions"}, false},
		{&state.SelfserviceMethodsDeviceauthnConfigPinMaxAttempts, nil, []string{"selfservice", "methods", "deviceauthn", "config", "pin_max_attempts"}, false},
	}
}

func identityListStringReadEntries(state *ProjectConfigResourceModel) []ListStringReadEntry {
	return []ListStringReadEntry{
		{&state.IdentitySecretsCipher, nil, []string{"secrets", "cipher"}, true},
		{&state.IdentitySecretsCookie, nil, []string{"secrets", "cookie"}, true},
		{&state.IdentitySecretsDefault, nil, []string{"secrets", "default"}, true},
		{&state.IdentitySecretsPagination, nil, []string{"secrets", "pagination"}, true},
		{&state.SelfserviceMethodsCaptchaConfigAllowedDomains, nil, []string{"selfservice", "methods", "captcha", "config", "allowed_domains"}, false},
		{&state.SelfserviceMethodsPasskeyConfigRPOrigins, nil, []string{"selfservice", "methods", "passkey", "config", "rp", "origins"}, false},
		{&state.WebAuthnRPOrigins, nil, []string{"selfservice", "methods", "webauthn", "config", "rp", "origins"}, false},
		{&state.SelfserviceMethodsDeviceauthnConfigAndroidAppIds, nil, []string{"selfservice", "methods", "deviceauthn", "config", "android_app_ids"}, false},
		{&state.SelfserviceMethodsDeviceauthnConfigIosAppIds, nil, []string{"selfservice", "methods", "deviceauthn", "config", "ios_app_ids"}, false},
	}
}

func identityMapStringReadEntries(state *ProjectConfigResourceModel) []MapStringReadEntry {
	return []MapStringReadEntry{
		{&state.OAuth2ProviderHeaders, nil, []string{"oauth2_provider", "headers"}, false},
		{&state.SMTPHeaders, nil, []string{"courier", "smtp", "headers"}, false},
	}
}

func oauth2StringReadEntries(state *ProjectConfigResourceModel) []StringReadEntry {
	return []StringReadEntry{
		{&state.OAuth2TTLAccessToken, &state.OAuth2AccessTokenLifespan, []string{"ttl", "access_token"}, false, false, false},
		{&state.OAuth2TTLRefreshToken, &state.OAuth2RefreshTokenLifespan, []string{"ttl", "refresh_token"}, false, false, false},
		{&state.OAuth2TTLAuthCode, &state.OAuth2AuthCodeLifespan, []string{"ttl", "auth_code"}, false, false, false},
		{&state.OAuth2TTLIDToken, &state.OAuth2IDTokenLifespan, []string{"ttl", "id_token"}, false, false, false},
		{&state.OAuth2TTLLoginConsentRequest, &state.OAuth2LoginConsentRequestLifespan, []string{"ttl", "login_consent_request"}, false, false, false},
		{&state.OAuth2StrategiesAccessToken, &state.OAuth2AccessTokenStrategy, []string{"strategies", "access_token"}, false, false, false},
		{&state.OAuth2StrategiesJWTScopeClaim, &state.OAuth2JWTScopeClaim, []string{"strategies", "jwt", "scope_claim"}, false, false, false},
		{&state.OAuth2StrategiesScope, &state.OAuth2ScopeStrategy, []string{"strategies", "scope"}, false, false, false},
		{&state.OAuth2URLsConsent, &state.OAuth2ConsentURL, []string{"urls", "consent"}, false, false, false},
		{&state.OAuth2URLsLogin, &state.OAuth2LoginURL, []string{"urls", "login"}, false, false, false},
		{&state.OAuth2URLsLogout, &state.OAuth2LogoutURL, []string{"urls", "logout"}, false, false, false},
		{&state.OAuth2URLsError, &state.OAuth2ErrorURL, []string{"urls", "error"}, false, false, false},
		{&state.OAuth2URLsSelfIssuer, &state.OAuth2IssuerURL, []string{"urls", "self", "issuer"}, false, false, false},
		{&state.OAuth2ServeCookiesSameSiteMode, &state.OAuth2CookiesSameSiteMode, []string{"serve", "cookies", "same_site_mode"}, false, false, false},
		{&state.OAuth2GrantJWTMaxTTL, nil, []string{"oauth2", "grant", "jwt", "max_ttl"}, false, false, false},
		{&state.OAuth2GrantRefreshTokenRotationGracePeriod, nil, []string{"oauth2", "grant", "refresh_token", "rotation_grace_period"}, false, false, false},
		{&state.OAuth2RefreshTokenHook, nil, []string{"oauth2", "refresh_token_hook"}, false, false, false},
		{&state.OAuth2TokenHook, nil, []string{"oauth2", "token_hook", "url"}, false, false, false},
		{&state.OIDCSubjectIdentifiersPairwiseSalt, nil, []string{"oidc", "subject_identifiers", "pairwise", "salt"}, false, false, false},
		{&state.OAuth2UrlsPostLogoutRedirect, nil, []string{"urls", "post_logout_redirect"}, false, false, false},
		{&state.OAuth2UrlsRegistration, nil, []string{"urls", "registration"}, false, false, false},
		{&state.OAuth2WebfingerOIDCDiscoveryAuthURL, nil, []string{"webfinger", "oidc_discovery", "auth_url"}, false, false, false},
		{&state.OAuth2WebfingerOIDCDiscoveryClientRegistrationURL, nil, []string{"webfinger", "oidc_discovery", "client_registration_url"}, false, false, false},
		{&state.OAuth2WebfingerOIDCDiscoveryJwksURL, nil, []string{"webfinger", "oidc_discovery", "jwks_url"}, false, false, false},
		{&state.OAuth2WebfingerOIDCDiscoveryTokenURL, nil, []string{"webfinger", "oidc_discovery", "token_url"}, false, false, false},
		{&state.OAuth2WebfingerOIDCDiscoveryUserinfoURL, nil, []string{"webfinger", "oidc_discovery", "userinfo_url"}, false, false, false},
		{&state.OAuth2TokenPrefix, nil, []string{"oauth2", "token_prefix"}, false, false, false},
		{&state.OAuth2DeviceAuthorizationTokenPollingInterval, nil, []string{"oauth2", "device_authorization", "token_polling_interval"}, false, false, false},
		{&state.OAuth2DeviceAuthorizationUserCodeEntropyPreset, nil, []string{"oauth2", "device_authorization", "user_code", "entropy_preset"}, false, false, false},
		{&state.OAuth2TTLDeviceUserCode, nil, []string{"ttl", "device_user_code"}, false, false, false},
		{&state.OAuth2UrlsDeviceSuccess, nil, []string{"urls", "device", "success"}, false, false, false},
		{&state.OAuth2UrlsDeviceVerification, nil, []string{"urls", "device", "verification"}, false, false, false},
		{&state.OAuth2WebfingerOIDCDiscoveryDeviceAuthorizationURL, nil, []string{"webfinger", "oidc_discovery", "device_authorization_url"}, false, false, false},
	}
}

func oauth2BoolReadEntries(state *ProjectConfigResourceModel) []BoolReadEntry {
	return []BoolReadEntry{
		{&state.OAuth2MirrorTopLevelClaims, nil, []string{"oauth2", "mirror_top_level_claims"}, false, nil},
		{&state.OAuth2PKCEEnforced, nil, []string{"oauth2", "pkce", "enforced"}, false, nil},
		{&state.OAuth2PKCEEnforcedForPublicClients, nil, []string{"oauth2", "pkce", "enforced_for_public_clients"}, false, nil},
		{&state.OAuth2ServeCookiesSameSiteLegacyWorkaround, &state.OAuth2CookiesSameSiteLegacyWorkaround, []string{"serve", "cookies", "same_site_legacy_workaround"}, false, nil},
		{&state.OAuth2ClientCredentialsDefaultGrantAllowedScope, nil, []string{"oauth2", "client_credentials", "default_grant_allowed_scope"}, false, nil},
		{&state.OAuth2ExcludeNotBeforeClaim, nil, []string{"oauth2", "exclude_not_before_claim"}, false, nil},
		{&state.OAuth2GrantJWTIATOptional, nil, []string{"oauth2", "grant", "jwt", "iat_optional"}, false, nil},
		{&state.OAuth2GrantJWTJTIOptional, nil, []string{"oauth2", "grant", "jwt", "jti_optional"}, false, nil},
		{&state.OIDCDynamicClientRegistrationEnabled, nil, []string{"oidc", "dynamic_client_registration", "enabled"}, false, nil},
		{&state.OAuth2PreserveExtClaims, nil, []string{"oauth2", "preserve_ext_claims"}, false, nil},
		{&state.OAuth2GrantJWTOmitAssertionAudience, nil, []string{"oauth2", "grant", "jwt", "omit_assertion_audience"}, false, nil},
	}
}

func oauth2Int64ReadEntries(state *ProjectConfigResourceModel) []Int64ReadEntry {
	return []Int64ReadEntry{
		{&state.OAuth2GrantRefreshTokenRotationGraceReuseCount, nil, []string{"oauth2", "grant", "refresh_token", "rotation_grace_reuse_count"}, false},
	}
}

func oauth2ListStringReadEntries(state *ProjectConfigResourceModel) []ListStringReadEntry {
	return []ListStringReadEntry{
		{&state.OIDCDynamicClientRegistrationDefaultScope, nil, []string{"oidc", "dynamic_client_registration", "default_scope"}, false},
		{&state.OIDCSubjectIdentifiersSupportedTypes, nil, []string{"oidc", "subject_identifiers", "supported_types"}, false},
		{&state.OAuth2SecretsCookie, nil, []string{"secrets", "cookie"}, true},
		{&state.OAuth2SecretsPagination, nil, []string{"secrets", "pagination"}, true},
		{&state.OAuth2SecretsSystem, nil, []string{"secrets", "system"}, true},
		{&state.OAuth2WebfingerJWKSBroadcastKeys, nil, []string{"webfinger", "jwks", "broadcast_keys"}, false},
		{&state.OAuth2WebfingerOIDCDiscoverySupportedClaims, nil, []string{"webfinger", "oidc_discovery", "supported_claims"}, false},
		{&state.OAuth2WebfingerOIDCDiscoverySupportedScope, nil, []string{"webfinger", "oidc_discovery", "supported_scope"}, false},
		{&state.OAuth2AllowedTopLevelClaims, nil, []string{"oauth2", "allowed_top_level_claims"}, false},
	}
}

func permissionStringReadEntries(state *ProjectConfigResourceModel) []StringReadEntry {
	return []StringReadEntry{
		{&state.KetoNamespaceConfiguration, nil, []string{"namespaces", "location"}, false, false, false},
	}
}

func permissionListStringReadEntries(state *ProjectConfigResourceModel) []ListStringReadEntry {
	return []ListStringReadEntry{
		{&state.KetoSecretsPagination, nil, []string{"secrets", "pagination"}, true},
	}
}
