// Code generated by go generate; DO NOT EDIT.
// Source: internal/codegen/cmd/generate/main.go
// Mappings: internal/codegen/mappings.yaml

package projectconfig

import (
	"context"
	"math"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
	ory "github.com/ory/client-go"
)

// Ensure imports are used.
var (
	_ *ory.Project
	_ context.Context
	_ attr.Value
)

// StringReadEntry maps a string state field to its config read path.
type StringReadEntry struct {
	Field      *types.String
	Deprecated *types.String // write to deprecated alias when it is non-null in state
	Keys       []string
	SkipEmpty  bool
}

// BoolReadEntry maps a bool state field to its config read path.
type BoolReadEntry struct {
	Field      *types.Bool
	Deprecated *types.Bool // write to deprecated alias when it is non-null in state
	Keys       []string
}

// Int64ReadEntry maps an int64 state field to its config read path.
type Int64ReadEntry struct {
	Field      *types.Int64
	Deprecated *types.Int64 // write to deprecated alias when it is non-null in state
	Keys       []string
}

// ListStringReadEntry maps a list(string) state field to its config read path.
type ListStringReadEntry struct {
	Field      *types.List
	Deprecated *types.List // write to deprecated alias when it is non-null in state
	Keys       []string
}

// MapStringReadEntry maps a map(string) state field to its config read path.
type MapStringReadEntry struct {
	Field      *types.Map
	Deprecated *types.Map // write to deprecated alias when it is non-null in state
	Keys       []string
}

// readSimpleFields reads all simple attributes from the API response into state.
func readSimpleFields(ctx context.Context, project *ory.Project, state *ProjectConfigResourceModel) {
	if project.Services.AccountExperience != nil {
		accountExperienceConfig := project.Services.AccountExperience.Config
		for _, e := range account_experienceStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedString(accountExperienceConfig, e.Keys...); ok {
					if !e.SkipEmpty || v != "" {
						*target = types.StringValue(v)
					}
				}
			}
		}
		for _, e := range account_experienceBoolReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedBool(accountExperienceConfig, e.Keys...); ok {
					*target = types.BoolValue(v)
				}
			}
		}
		for _, e := range account_experienceListStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(accountExperienceConfig, e.Keys...); v != nil {
					if arr, ok := v.([]interface{}); ok {
						strs := make([]string, 0, len(arr))
						allStrings := true
						for _, item := range arr {
							if s, ok := item.(string); ok {
								strs = append(strs, s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							listVal, diags := types.ListValueFrom(ctx, types.StringType, strs)
							if !diags.HasError() {
								*target = listVal
							}
						}
					}
				}
			}
		}
	}
	if project.Services.Identity != nil {
		identityConfig := project.Services.Identity.Config
		for _, e := range identityStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedString(identityConfig, e.Keys...); ok {
					if !e.SkipEmpty || v != "" {
						*target = types.StringValue(v)
					}
				}
			}
		}
		for _, e := range identityBoolReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedBool(identityConfig, e.Keys...); ok {
					*target = types.BoolValue(v)
				}
			}
		}
		for _, e := range identityInt64ReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedFloat(identityConfig, e.Keys...); ok {
					if v == math.Trunc(v) {
						*target = types.Int64Value(int64(v))
					}
				}
			}
		}
		for _, e := range identityListStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(identityConfig, e.Keys...); v != nil {
					if arr, ok := v.([]interface{}); ok {
						strs := make([]string, 0, len(arr))
						allStrings := true
						for _, item := range arr {
							if s, ok := item.(string); ok {
								strs = append(strs, s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							listVal, diags := types.ListValueFrom(ctx, types.StringType, strs)
							if !diags.HasError() {
								*target = listVal
							}
						}
					}
				}
			}
		}
		for _, e := range identityMapStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(identityConfig, e.Keys...); v != nil {
					if m, ok := v.(map[string]interface{}); ok {
						strMap := make(map[string]attr.Value, len(m))
						allStrings := true
						for k, val := range m {
							if s, ok := val.(string); ok {
								strMap[k] = types.StringValue(s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							mapVal, diags := types.MapValue(types.StringType, strMap)
							if !diags.HasError() {
								*target = mapVal
							}
						}
					}
				}
			}
		}
	}
	if project.Services.Oauth2 != nil {
		oauth2Config := project.Services.Oauth2.Config
		for _, e := range oauth2StringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedString(oauth2Config, e.Keys...); ok {
					if !e.SkipEmpty || v != "" {
						*target = types.StringValue(v)
					}
				}
			}
		}
		for _, e := range oauth2BoolReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedBool(oauth2Config, e.Keys...); ok {
					*target = types.BoolValue(v)
				}
			}
		}
		for _, e := range oauth2ListStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(oauth2Config, e.Keys...); v != nil {
					if arr, ok := v.([]interface{}); ok {
						strs := make([]string, 0, len(arr))
						allStrings := true
						for _, item := range arr {
							if s, ok := item.(string); ok {
								strs = append(strs, s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							listVal, diags := types.ListValueFrom(ctx, types.StringType, strs)
							if !diags.HasError() {
								*target = listVal
							}
						}
					}
				}
			}
		}
	}
	if project.Services.Permission != nil {
		permissionConfig := project.Services.Permission.Config
		for _, e := range permissionStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v, ok := getNestedString(permissionConfig, e.Keys...); ok {
					if !e.SkipEmpty || v != "" {
						*target = types.StringValue(v)
					}
				}
			}
		}
		for _, e := range permissionListStringReadEntries(state) {
			target := e.Field
			if target.IsNull() && e.Deprecated != nil && !e.Deprecated.IsNull() {
				target = e.Deprecated
			}
			if !target.IsNull() {
				if v := getNestedValue(permissionConfig, e.Keys...); v != nil {
					if arr, ok := v.([]interface{}); ok {
						strs := make([]string, 0, len(arr))
						allStrings := true
						for _, item := range arr {
							if s, ok := item.(string); ok {
								strs = append(strs, s)
							} else {
								allStrings = false
								break
							}
						}
						if allStrings {
							listVal, diags := types.ListValueFrom(ctx, types.StringType, strs)
							if !diags.HasError() {
								*target = listVal
							}
						}
					}
				}
			}
		}
	}
}

func account_experienceStringReadEntries(state *ProjectConfigResourceModel) []StringReadEntry {
	return []StringReadEntry{
		{&state.AccountExperienceLocale, nil, []string{"default_locale"}, true},
		{&state.AccountExperienceFaviconDark, nil, []string{"favicon_dark"}, true},
		{&state.AccountExperienceFaviconLight, nil, []string{"favicon_light"}, true},
		{&state.AccountExperienceLocaleBehavior, nil, []string{"locale_behavior"}, true},
		{&state.AccountExperienceLogoDark, nil, []string{"logo_dark"}, true},
		{&state.AccountExperienceLogoLight, nil, []string{"logo_light"}, true},
		{&state.AccountExperienceThemeVariablesDark, nil, []string{"theme_variables_dark"}, true},
		{&state.AccountExperienceThemeVariablesLight, nil, []string{"theme_variables_light"}, true},
	}
}

func account_experienceBoolReadEntries(state *ProjectConfigResourceModel) []BoolReadEntry {
	return []BoolReadEntry{
		{&state.DisableAccountExperienceWelcomeScreen, nil, []string{"disable_welcome_screen"}},
		{&state.EnableAXV2, nil, []string{"enable_ax_v2"}},
	}
}

func account_experienceListStringReadEntries(state *ProjectConfigResourceModel) []ListStringReadEntry {
	return []ListStringReadEntry{
		{&state.AccountExperienceEnabledLocales, nil, []string{"enabled_locales"}},
	}
}

func identityStringReadEntries(state *ProjectConfigResourceModel) []StringReadEntry {
	return []StringReadEntry{
		{&state.SessionLifespan, nil, []string{"session", "lifespan"}, false},
		{&state.SessionCookieSameSite, nil, []string{"session", "cookie", "same_site"}, false},
		{&state.SessionWhoamiRequiredAAL, nil, []string{"session", "whoami", "required_aal"}, false},
		{&state.SelfserviceFlowsLoginUIURL, &state.LoginUIURL, []string{"selfservice", "flows", "login", "ui_url"}, false},
		{&state.SelfserviceFlowsRegistrationUIURL, &state.RegistrationUIURL, []string{"selfservice", "flows", "registration", "ui_url"}, false},
		{&state.SelfserviceFlowsRecoveryUIURL, &state.RecoveryUIURL, []string{"selfservice", "flows", "recovery", "ui_url"}, false},
		{&state.SelfserviceFlowsVerificationUIURL, &state.VerificationUIURL, []string{"selfservice", "flows", "verification", "ui_url"}, false},
		{&state.SelfserviceFlowsSettingsUIURL, &state.SettingsUIURL, []string{"selfservice", "flows", "settings", "ui_url"}, false},
		{&state.SelfserviceFlowsErrorUIURL, &state.ErrorUIURL, []string{"selfservice", "flows", "error", "ui_url"}, false},
		{&state.SelfserviceMethodsCodeConfigLifespan, &state.CodeLifespan, []string{"selfservice", "methods", "code", "config", "lifespan"}, false},
		{&state.SelfserviceFlowsLoginStyle, &state.LoginStyle, []string{"selfservice", "flows", "login", "style"}, false},
		{&state.SelfserviceFlowsSettingsLifespan, &state.SettingsLifespan, []string{"selfservice", "flows", "settings", "lifespan"}, false},
		{&state.SelfserviceFlowsSettingsPrivilegedSessionMaxAge, &state.SettingsPrivilegedSessionMaxAge, []string{"selfservice", "flows", "settings", "privileged_session_max_age"}, false},
		{&state.SelfserviceFlowsSettingsRequiredAAL, &state.RequiredAAL, []string{"selfservice", "flows", "settings", "required_aal"}, false},
		{&state.SelfserviceFlowsVerificationUse, &state.VerificationUse, []string{"selfservice", "flows", "verification", "use"}, false},
		{&state.SelfserviceFlowsVerificationLifespan, &state.VerificationLifespan, []string{"selfservice", "flows", "verification", "lifespan"}, false},
		{&state.CourierSMTPFromAddress, &state.SMTPFromAddress, []string{"courier", "smtp", "from_address"}, false},
		{&state.CourierSMTPFromName, &state.SMTPFromName, []string{"courier", "smtp", "from_name"}, false},
		{&state.SelfserviceMethodsTOTPConfigIssuer, &state.TOTPIssuer, []string{"selfservice", "methods", "totp", "config", "issuer"}, false},
		{&state.SelfserviceMethodsWebAuthnConfigRPDisplayName, &state.WebAuthnRPDisplayName, []string{"selfservice", "methods", "webauthn", "config", "rp", "display_name"}, false},
		{&state.SelfserviceMethodsWebAuthnConfigRPID, &state.WebAuthnRPID, []string{"selfservice", "methods", "webauthn", "config", "rp", "id"}, false},
		{&state.CourierDeliveryStrategy, nil, []string{"courier", "delivery_strategy"}, false},
		{&state.CookiesSameSite, nil, []string{"cookies", "same_site"}, false},
		{&state.CourierHTTPRequestConfigAuthAPIKeyIn, nil, []string{"courier", "http", "request_config", "auth", "config", "in"}, false},
		{&state.CourierHTTPRequestConfigAuthAPIKeyName, nil, []string{"courier", "http", "request_config", "auth", "config", "name"}, false},
		{&state.CourierHTTPRequestConfigAuthAPIKeyValue, nil, []string{"courier", "http", "request_config", "auth", "config", "value"}, false},
		{&state.CourierHTTPRequestConfigAuthBasicAuthPassword, nil, []string{"courier", "http", "request_config", "auth", "config", "password"}, false},
		{&state.CourierHTTPRequestConfigAuthBasicAuthUser, nil, []string{"courier", "http", "request_config", "auth", "config", "user"}, false},
		{&state.CourierHTTPRequestConfigBody, nil, []string{"courier", "http", "request_config", "body"}, false},
		{&state.CourierHTTPRequestConfigURL, nil, []string{"courier", "http", "request_config", "url"}, false},
		{&state.CourierSMTPLocalName, nil, []string{"courier", "smtp", "local_name"}, false},
		{&state.CourierTemplatesLoginCodeValidEmailBodyHTML, nil, []string{"courier", "templates", "login_code", "valid", "email", "body", "html"}, false},
		{&state.CourierTemplatesLoginCodeValidEmailBodyPlaintext, nil, []string{"courier", "templates", "login_code", "valid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesLoginCodeValidEmailSubject, nil, []string{"courier", "templates", "login_code", "valid", "email", "subject"}, false},
		{&state.CourierTemplatesLoginCodeValidSMSBodyPlaintext, nil, []string{"courier", "templates", "login_code", "valid", "sms", "body", "plaintext"}, false},
		{&state.CourierTemplatesRecoveryCodeInvalidEmailBodyHTML, nil, []string{"courier", "templates", "recovery_code", "invalid", "email", "body", "html"}, false},
		{&state.CourierTemplatesRecoveryCodeInvalidEmailBodyPlaintext, nil, []string{"courier", "templates", "recovery_code", "invalid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesRecoveryCodeInvalidEmailSubject, nil, []string{"courier", "templates", "recovery_code", "invalid", "email", "subject"}, false},
		{&state.CourierTemplatesRecoveryCodeValidEmailBodyHTML, nil, []string{"courier", "templates", "recovery_code", "valid", "email", "body", "html"}, false},
		{&state.CourierTemplatesRecoveryCodeValidEmailBodyPlaintext, nil, []string{"courier", "templates", "recovery_code", "valid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesRecoveryCodeValidEmailSubject, nil, []string{"courier", "templates", "recovery_code", "valid", "email", "subject"}, false},
		{&state.CourierTemplatesRecoveryInvalidEmailBodyHTML, nil, []string{"courier", "templates", "recovery", "invalid", "email", "body", "html"}, false},
		{&state.CourierTemplatesRecoveryInvalidEmailBodyPlaintext, nil, []string{"courier", "templates", "recovery", "invalid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesRecoveryInvalidEmailSubject, nil, []string{"courier", "templates", "recovery", "invalid", "email", "subject"}, false},
		{&state.CourierTemplatesRecoveryValidEmailBodyHTML, nil, []string{"courier", "templates", "recovery", "valid", "email", "body", "html"}, false},
		{&state.CourierTemplatesRecoveryValidEmailBodyPlaintext, nil, []string{"courier", "templates", "recovery", "valid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesRecoveryValidEmailSubject, nil, []string{"courier", "templates", "recovery", "valid", "email", "subject"}, false},
		{&state.CourierTemplatesRegistrationCodeValidEmailBodyHTML, nil, []string{"courier", "templates", "registration_code", "valid", "email", "body", "html"}, false},
		{&state.CourierTemplatesRegistrationCodeValidEmailBodyPlaintext, nil, []string{"courier", "templates", "registration_code", "valid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesRegistrationCodeValidEmailSubject, nil, []string{"courier", "templates", "registration_code", "valid", "email", "subject"}, false},
		{&state.CourierTemplatesRegistrationCodeValidSMSBodyPlaintext, nil, []string{"courier", "templates", "registration_code", "valid", "sms", "body", "plaintext"}, false},
		{&state.CourierTemplatesVerificationCodeInvalidEmailBodyHTML, nil, []string{"courier", "templates", "verification_code", "invalid", "email", "body", "html"}, false},
		{&state.CourierTemplatesVerificationCodeInvalidEmailBodyPlaintext, nil, []string{"courier", "templates", "verification_code", "invalid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesVerificationCodeInvalidEmailSubject, nil, []string{"courier", "templates", "verification_code", "invalid", "email", "subject"}, false},
		{&state.CourierTemplatesVerificationCodeValidEmailBodyHTML, nil, []string{"courier", "templates", "verification_code", "valid", "email", "body", "html"}, false},
		{&state.CourierTemplatesVerificationCodeValidEmailBodyPlaintext, nil, []string{"courier", "templates", "verification_code", "valid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesVerificationCodeValidEmailSubject, nil, []string{"courier", "templates", "verification_code", "valid", "email", "subject"}, false},
		{&state.CourierTemplatesVerificationCodeValidSMSBodyPlaintext, nil, []string{"courier", "templates", "verification_code", "valid", "sms", "body", "plaintext"}, false},
		{&state.CourierTemplatesVerificationInvalidEmailBodyHTML, nil, []string{"courier", "templates", "verification", "invalid", "email", "body", "html"}, false},
		{&state.CourierTemplatesVerificationInvalidEmailBodyPlaintext, nil, []string{"courier", "templates", "verification", "invalid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesVerificationInvalidEmailSubject, nil, []string{"courier", "templates", "verification", "invalid", "email", "subject"}, false},
		{&state.CourierTemplatesVerificationValidEmailBodyHTML, nil, []string{"courier", "templates", "verification", "valid", "email", "body", "html"}, false},
		{&state.CourierTemplatesVerificationValidEmailBodyPlaintext, nil, []string{"courier", "templates", "verification", "valid", "email", "body", "plaintext"}, false},
		{&state.CourierTemplatesVerificationValidEmailSubject, nil, []string{"courier", "templates", "verification", "valid", "email", "subject"}, false},
		{&state.FeatureFlagsCacheableSessionsMaxAge, nil, []string{"feature_flags", "cacheable_sessions_max_age"}, false},
		{&state.OAuth2ProviderURL, nil, []string{"oauth2_provider", "url"}, false},
		{&state.SelfserviceDefaultBrowserReturnURL, nil, []string{"selfservice", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsLoginAfterCodeDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "code", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsLoginAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsLoginAfterLookupSecretDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "lookup_secret", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsLoginAfterOIDCDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "oidc", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsLoginAfterPasskeyDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "passkey", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsLoginAfterPasswordDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "password", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsLoginAfterTOTPDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "totp", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsLoginAfterWebAuthnDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "login", "after", "webauthn", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsLoginLifespan, nil, []string{"selfservice", "flows", "login", "lifespan"}, false},
		{&state.SelfserviceFlowsLogoutAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "logout", "after", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsRecoveryAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "recovery", "after", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsRecoveryLifespan, nil, []string{"selfservice", "flows", "recovery", "lifespan"}, false},
		{&state.SelfserviceFlowsRecoveryUse, nil, []string{"selfservice", "flows", "recovery", "use"}, false},
		{&state.SelfserviceFlowsRegistrationAfterCodeDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "code", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsRegistrationAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsRegistrationAfterOIDCDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "oidc", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsRegistrationAfterPasskeyDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "passkey", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsRegistrationAfterPasswordDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "password", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsRegistrationAfterWebAuthnDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "registration", "after", "webauthn", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsRegistrationLifespan, nil, []string{"selfservice", "flows", "registration", "lifespan"}, false},
		{&state.SelfserviceFlowsSettingsAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsSettingsAfterLookupSecretDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "lookup_secret", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsSettingsAfterOIDCDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "oidc", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsSettingsAfterPasskeyDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "passkey", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsSettingsAfterPasswordDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "password", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsSettingsAfterProfileDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "profile", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsSettingsAfterTOTPDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "totp", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsSettingsAfterWebAuthnDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "settings", "after", "webauthn", "default_browser_return_url"}, false},
		{&state.SelfserviceFlowsVerificationAfterDefaultBrowserReturnURL, nil, []string{"selfservice", "flows", "verification", "after", "default_browser_return_url"}, false},
		{&state.SelfserviceMethodsLinkConfigBaseURL, nil, []string{"selfservice", "methods", "link", "config", "base_url"}, false},
		{&state.SelfserviceMethodsLinkConfigLifespan, nil, []string{"selfservice", "methods", "link", "config", "lifespan"}, false},
		{&state.SelfserviceMethodsOIDCConfigBaseRedirectURI, nil, []string{"selfservice", "methods", "oidc", "config", "base_redirect_uri"}, false},
		{&state.SelfserviceMethodsPasskeyConfigRPDisplayName, nil, []string{"selfservice", "methods", "passkey", "config", "rp", "display_name"}, false},
		{&state.SelfserviceMethodsPasskeyConfigRPID, nil, []string{"selfservice", "methods", "passkey", "config", "rp", "id"}, false},
		{&state.SelfserviceMethodsWebAuthnConfigRPIcon, nil, []string{"selfservice", "methods", "webauthn", "config", "rp", "icon"}, false},
		{&state.PreviewDefaultReadConsistencyLevel, nil, []string{"preview", "default_read_consistency_level"}, false},
		{&state.SelfserviceMethodsCaptchaConfigCFTurnstileSecret, nil, []string{"selfservice", "methods", "captcha", "config", "cf_turnstile", "secret"}, false},
		{&state.SelfserviceMethodsCaptchaConfigCFTurnstileSitekey, nil, []string{"selfservice", "methods", "captcha", "config", "cf_turnstile", "sitekey"}, false},
		{&state.CourierHTTPRequestConfigAuthType, nil, []string{"courier", "http", "request_config", "auth", "type"}, false},
		{&state.CourierHTTPRequestConfigMethod, nil, []string{"courier", "http", "request_config", "method"}, false},
		{&state.SMTPConnectionURI, nil, []string{"courier", "smtp", "connection_uri"}, true},
	}
}

func identityBoolReadEntries(state *ProjectConfigResourceModel) []BoolReadEntry {
	return []BoolReadEntry{
		{&state.SessionCookiePersistent, nil, []string{"session", "cookie", "persistent"}},
		{&state.SelfserviceMethodsPasswordEnabled, &state.EnablePassword, []string{"selfservice", "methods", "password", "enabled"}},
		{&state.SelfserviceMethodsCodeEnabled, &state.EnableCode, []string{"selfservice", "methods", "code", "enabled"}},
		{&state.SelfserviceMethodsCodeMFAEnabled, &state.CodeMFAEnabled, []string{"selfservice", "methods", "code", "mfa_enabled"}},
		{&state.SelfserviceMethodsOIDCEnabled, &state.EnableOIDC, []string{"selfservice", "methods", "oidc", "enabled"}},
		{&state.SelfserviceMethodsOIDCEnableAutoLinkPolicy, &state.EnableOIDCAutoLinkPolicy, []string{"selfservice", "methods", "oidc", "enable_auto_link_policy"}},
		{&state.SelfserviceMethodsTOTPEnabled, &state.EnableTOTP, []string{"selfservice", "methods", "totp", "enabled"}},
		{&state.SelfserviceMethodsWebAuthnEnabled, &state.EnableWebAuthn, []string{"selfservice", "methods", "webauthn", "enabled"}},
		{&state.SelfserviceMethodsPasskeyEnabled, &state.EnablePasskey, []string{"selfservice", "methods", "passkey", "enabled"}},
		{&state.SelfserviceMethodsLookupSecretEnabled, &state.EnableLookupSecret, []string{"selfservice", "methods", "lookup_secret", "enabled"}},
		{&state.SelfserviceMethodsProfileEnabled, &state.EnableProfile, []string{"selfservice", "methods", "profile", "enabled"}},
		{&state.SelfserviceMethodsCodeConfigMissingCredentialFallbackEnabled, &state.CodeMissingCredentialFallbackEnabled, []string{"selfservice", "methods", "code", "config", "missing_credential_fallback_enabled"}},
		{&state.SelfserviceMethodsPasswordConfigHaveIBeenPwnedEnabled, &state.PasswordCheckHaveIBeenPwned, []string{"selfservice", "methods", "password", "config", "haveibeenpwned_enabled"}},
		{&state.SelfserviceMethodsPasswordConfigIdentifierSimilarityCheckEnabled, &state.PasswordIdentifierSimilarity, []string{"selfservice", "methods", "password", "config", "identifier_similarity_check_enabled"}},
		{&state.SelfserviceFlowsRecoveryEnabled, &state.EnableRecovery, []string{"selfservice", "flows", "recovery", "enabled"}},
		{&state.SelfserviceFlowsVerificationEnabled, &state.EnableVerification, []string{"selfservice", "flows", "verification", "enabled"}},
		{&state.SelfserviceFlowsRegistrationEnabled, &state.EnableRegistration, []string{"selfservice", "flows", "registration", "enabled"}},
		{&state.SelfserviceFlowsVerificationNotifyUnknownRecipients, &state.VerificationNotifyUnknownRecipients, []string{"selfservice", "flows", "verification", "notify_unknown_recipients"}},
		{&state.SelfserviceMethodsWebAuthnConfigPasswordless, &state.WebAuthnPasswordless, []string{"selfservice", "methods", "webauthn", "config", "passwordless"}},
		{&state.FeatureFlagsCacheableSessions, nil, []string{"feature_flags", "cacheable_sessions"}},
		{&state.FeatureFlagsChooseRecoveryAddress, nil, []string{"feature_flags", "choose_recovery_address"}},
		{&state.FeatureFlagsFasterSessionExtend, nil, []string{"feature_flags", "faster_session_extend"}},
		{&state.FeatureFlagsLegacyContinueWithVerificationUI, nil, []string{"feature_flags", "legacy_continue_with_verification_ui"}},
		{&state.FeatureFlagsLegacyOIDCRegistrationNodeGroup, nil, []string{"feature_flags", "legacy_oidc_registration_node_group"}},
		{&state.FeatureFlagsLegacyRequireVerifiedLoginError, nil, []string{"feature_flags", "legacy_require_verified_login_error"}},
		{&state.FeatureFlagsUseContinueWithTransitions, nil, []string{"feature_flags", "use_continue_with_transitions"}},
		{&state.SelfserviceFlowsRecoveryNotifyUnknownRecipients, nil, []string{"selfservice", "flows", "recovery", "notify_unknown_recipients"}},
		{&state.SelfserviceFlowsRegistrationEnableLegacyOneStep, nil, []string{"selfservice", "flows", "registration", "enable_legacy_one_step"}},
		{&state.SelfserviceFlowsRegistrationLoginHints, nil, []string{"selfservice", "flows", "registration", "login_hints"}},
		{&state.SelfserviceMethodsCodePasswordlessEnabled, nil, []string{"selfservice", "methods", "code", "passwordless_enabled"}},
		{&state.SelfserviceMethodsCodePasswordlessLoginFallbackEnabled, nil, []string{"selfservice", "methods", "code", "passwordless_login_fallback_enabled"}},
		{&state.SelfserviceMethodsLinkEnabled, nil, []string{"selfservice", "methods", "link", "enabled"}},
		{&state.SelfserviceMethodsPasswordConfigIgnoreNetworkErrors, nil, []string{"selfservice", "methods", "password", "config", "ignore_network_errors"}},
		{&state.SelfserviceMethodsSAMLEnabled, nil, []string{"selfservice", "methods", "saml", "enabled"}},
		{&state.FeatureFlagsPasswordProfileRegistrationNodeGroup, nil, []string{"feature_flags", "password_profile_registration_node_group"}},
		{&state.OAuth2ProviderOverrideReturnTo, nil, []string{"oauth2_provider", "override_return_to"}},
		{&state.SecurityAccountEnumerationMitigate, nil, []string{"security", "account_enumeration", "mitigate"}},
		{&state.SelfserviceMethodsCaptchaConfigBYO, nil, []string{"selfservice", "methods", "captcha", "config", "byo"}},
		{&state.SelfserviceMethodsCaptchaConfigLegacyInjectNode, nil, []string{"selfservice", "methods", "captcha", "config", "legacy_inject_node"}},
		{&state.SelfserviceMethodsCaptchaEnabled, nil, []string{"selfservice", "methods", "captcha", "enabled"}},
	}
}

func identityInt64ReadEntries(state *ProjectConfigResourceModel) []Int64ReadEntry {
	return []Int64ReadEntry{
		{&state.SelfserviceMethodsPasswordConfigMinPasswordLength, &state.PasswordMinLength, []string{"selfservice", "methods", "password", "config", "min_password_length"}},
		{&state.SelfserviceMethodsPasswordConfigMaxBreaches, &state.PasswordMaxBreaches, []string{"selfservice", "methods", "password", "config", "max_breaches"}},
		{&state.SelfserviceMethodsCodeConfigMaxSubmissions, nil, []string{"selfservice", "methods", "code", "max_submissions"}},
	}
}

func identityListStringReadEntries(state *ProjectConfigResourceModel) []ListStringReadEntry {
	return []ListStringReadEntry{
		{&state.IdentitySecretsCipher, nil, []string{"secrets", "cipher"}},
		{&state.IdentitySecretsCookie, nil, []string{"secrets", "cookie"}},
		{&state.IdentitySecretsDefault, nil, []string{"secrets", "default"}},
		{&state.IdentitySecretsPagination, nil, []string{"secrets", "pagination"}},
		{&state.SelfserviceMethodsCaptchaConfigAllowedDomains, nil, []string{"selfservice", "methods", "captcha", "config", "allowed_domains"}},
		{&state.SelfserviceMethodsPasskeyConfigRPOrigins, nil, []string{"selfservice", "methods", "passkey", "config", "rp", "origins"}},
		{&state.WebAuthnRPOrigins, nil, []string{"selfservice", "methods", "webauthn", "config", "rp", "origins"}},
	}
}

func identityMapStringReadEntries(state *ProjectConfigResourceModel) []MapStringReadEntry {
	return []MapStringReadEntry{
		{&state.OAuth2ProviderHeaders, nil, []string{"oauth2_provider", "headers"}},
		{&state.SMTPHeaders, nil, []string{"courier", "smtp", "headers"}},
	}
}

func oauth2StringReadEntries(state *ProjectConfigResourceModel) []StringReadEntry {
	return []StringReadEntry{
		{&state.OAuth2TTLAccessToken, &state.OAuth2AccessTokenLifespan, []string{"ttl", "access_token"}, false},
		{&state.OAuth2TTLRefreshToken, &state.OAuth2RefreshTokenLifespan, []string{"ttl", "refresh_token"}, false},
		{&state.OAuth2TTLAuthCode, &state.OAuth2AuthCodeLifespan, []string{"ttl", "auth_code"}, false},
		{&state.OAuth2TTLIDToken, &state.OAuth2IDTokenLifespan, []string{"ttl", "id_token"}, false},
		{&state.OAuth2TTLLoginConsentRequest, &state.OAuth2LoginConsentRequestLifespan, []string{"ttl", "login_consent_request"}, false},
		{&state.OAuth2StrategiesAccessToken, &state.OAuth2AccessTokenStrategy, []string{"strategies", "access_token"}, false},
		{&state.OAuth2StrategiesJWTScopeClaim, &state.OAuth2JWTScopeClaim, []string{"strategies", "jwt", "scope_claim"}, false},
		{&state.OAuth2StrategiesScope, &state.OAuth2ScopeStrategy, []string{"strategies", "scope"}, false},
		{&state.OAuth2URLsConsent, &state.OAuth2ConsentURL, []string{"urls", "consent"}, false},
		{&state.OAuth2URLsLogin, &state.OAuth2LoginURL, []string{"urls", "login"}, false},
		{&state.OAuth2URLsLogout, &state.OAuth2LogoutURL, []string{"urls", "logout"}, false},
		{&state.OAuth2URLsError, &state.OAuth2ErrorURL, []string{"urls", "error"}, false},
		{&state.OAuth2URLsSelfIssuer, &state.OAuth2IssuerURL, []string{"urls", "self", "issuer"}, false},
		{&state.OAuth2ServeCookiesSameSiteMode, &state.OAuth2CookiesSameSiteMode, []string{"serve", "cookies", "same_site_mode"}, false},
		{&state.OAuth2GrantJWTMaxTTL, nil, []string{"oauth2", "grant", "jwt", "max_ttl"}, false},
		{&state.OAuth2GrantRefreshTokenRotationGracePeriod, nil, []string{"oauth2", "grant", "refresh_token_rotation_grace_period"}, false},
		{&state.OAuth2RefreshTokenHook, nil, []string{"oauth2", "refresh_token_hook"}, false},
		{&state.OAuth2TokenHook, nil, []string{"oauth2", "token_hook", "url"}, false},
		{&state.OIDCSubjectIdentifiersPairwiseSalt, nil, []string{"oidc", "subject_identifiers", "pairwise_salt"}, false},
		{&state.OAuth2UrlsPostLogoutRedirect, nil, []string{"urls", "post_logout_redirect"}, false},
		{&state.OAuth2UrlsRegistration, nil, []string{"urls", "registration"}, false},
		{&state.OAuth2WebfingerOIDCDiscoveryAuthURL, nil, []string{"webfinger", "oidc_discovery", "auth_url"}, false},
		{&state.OAuth2WebfingerOIDCDiscoveryClientRegistrationURL, nil, []string{"webfinger", "oidc_discovery", "client_registration_url"}, false},
		{&state.OAuth2WebfingerOIDCDiscoveryJwksURL, nil, []string{"webfinger", "oidc_discovery", "jwks_url"}, false},
		{&state.OAuth2WebfingerOIDCDiscoveryTokenURL, nil, []string{"webfinger", "oidc_discovery", "token_url"}, false},
		{&state.OAuth2WebfingerOIDCDiscoveryUserinfoURL, nil, []string{"webfinger", "oidc_discovery", "userinfo_url"}, false},
	}
}

func oauth2BoolReadEntries(state *ProjectConfigResourceModel) []BoolReadEntry {
	return []BoolReadEntry{
		{&state.OAuth2MirrorTopLevelClaims, nil, []string{"oauth2", "mirror_top_level_claims"}},
		{&state.OAuth2PKCEEnforced, nil, []string{"oauth2", "pkce", "enforced"}},
		{&state.OAuth2PKCEEnforcedForPublicClients, nil, []string{"oauth2", "pkce", "enforced_for_public_clients"}},
		{&state.OAuth2ServeCookiesSameSiteLegacyWorkaround, &state.OAuth2CookiesSameSiteLegacyWorkaround, []string{"serve", "cookies", "same_site_legacy_workaround"}},
		{&state.OAuth2ClientCredentialsDefaultGrantAllowedScope, nil, []string{"oauth2", "client_credentials", "default_grant_allowed_scope"}},
		{&state.OAuth2ExcludeNotBeforeClaim, nil, []string{"oauth2", "exclude_not_before_claim"}},
		{&state.OAuth2GrantJWTIATOptional, nil, []string{"oauth2", "grant", "jwt", "iat_optional"}},
		{&state.OAuth2GrantJWTJTIOptional, nil, []string{"oauth2", "grant", "jwt", "jti_optional"}},
		{&state.OIDCDynamicClientRegistrationEnabled, nil, []string{"oidc", "dynamic_client_registration", "enabled"}},
	}
}

func oauth2ListStringReadEntries(state *ProjectConfigResourceModel) []ListStringReadEntry {
	return []ListStringReadEntry{
		{&state.OIDCDynamicClientRegistrationDefaultScope, nil, []string{"oidc", "dynamic_client_registration", "default_scope"}},
		{&state.OIDCSubjectIdentifiersSupportedTypes, nil, []string{"oidc", "subject_identifiers", "supported_types"}},
		{&state.OAuth2SecretsCookie, nil, []string{"secrets", "cookie"}},
		{&state.OAuth2SecretsPagination, nil, []string{"secrets", "pagination"}},
		{&state.OAuth2SecretsSystem, nil, []string{"secrets", "system"}},
		{&state.OAuth2WebfingerJWKSBroadcastKeys, nil, []string{"webfinger", "jwks", "broadcast_keys"}},
		{&state.OAuth2WebfingerOIDCDiscoverySupportedClaims, nil, []string{"webfinger", "oidc_discovery", "supported_claims"}},
		{&state.OAuth2WebfingerOIDCDiscoverySupportedScope, nil, []string{"webfinger", "oidc_discovery", "supported_scope"}},
		{&state.OAuth2AllowedTopLevelClaims, nil, []string{"oauth2", "allowed_top_level_claims"}},
	}
}

func permissionStringReadEntries(state *ProjectConfigResourceModel) []StringReadEntry {
	return []StringReadEntry{
		{&state.KetoNamespaceConfiguration, nil, []string{"namespaces", "location"}, false},
	}
}

func permissionListStringReadEntries(state *ProjectConfigResourceModel) []ListStringReadEntry {
	return []ListStringReadEntry{
		{&state.KetoSecretsPagination, nil, []string{"secrets", "pagination"}},
	}
}
