// Code generated by go generate; DO NOT EDIT.
// Source: internal/codegen/cmd/generate/main.go
// Mappings: internal/codegen/mappings.yaml

package projectconfig

import (
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure imported packages are used.
var (
	_ = stringvalidator.OneOf
	_ = booldefault.StaticBool
	_ = int64default.StaticInt64
	_ validator.String
	_ = types.StringType
)

// simpleSchemaAttributes returns the schema attributes for all simple
// (string, bool, int64, list_string, map_string) configuration fields.
// Complex nested types (tokenizer templates, courier channels, etc.) are
// defined separately.
func simpleSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"session_lifespan": schema.StringAttribute{
			Description: "Session duration (e.g., '24h0m0s').",
			Optional:    true,
		},
		"session_cookie_same_site": schema.StringAttribute{
			Description: "SameSite cookie attribute (Lax, Strict, None).",
			Optional:    true,
		},
		"session_cookie_persistent": schema.BoolAttribute{
			Description: "Enable persistent session cookies (survive browser close).",
			Optional:    true,
		},
		"session_whoami_required_aal": schema.StringAttribute{
			Description: "Required AAL for session whoami endpoint: 'aal1', 'aal2', or 'highest_available'.",
			Optional:    true,
		},
		"oauth2_ttl_access_token": schema.StringAttribute{
			Description: "OAuth2 access token lifespan (e.g., '1h', '30m'). Requires Hydra service.",
			Optional:    true,
		},
		"oauth2_access_token_lifespan": schema.StringAttribute{
			Description:        "OAuth2 access token lifespan (e.g., '1h', '30m'). Requires Hydra service.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_ttl_access_token instead. This attribute will be removed in a future major version.",
		},
		"oauth2_ttl_refresh_token": schema.StringAttribute{
			Description: "OAuth2 refresh token lifespan (e.g., '720h' for 30 days). Requires Hydra service.",
			Optional:    true,
		},
		"oauth2_refresh_token_lifespan": schema.StringAttribute{
			Description:        "OAuth2 refresh token lifespan (e.g., '720h' for 30 days). Requires Hydra service.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_ttl_refresh_token instead. This attribute will be removed in a future major version.",
		},
		"oauth2_ttl_auth_code": schema.StringAttribute{
			Description: "OAuth2 authorization code lifespan (e.g., '30m'). Requires Hydra service.",
			Optional:    true,
		},
		"oauth2_auth_code_lifespan": schema.StringAttribute{
			Description:        "OAuth2 authorization code lifespan (e.g., '30m'). Requires Hydra service.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_ttl_auth_code instead. This attribute will be removed in a future major version.",
		},
		"oauth2_ttl_id_token": schema.StringAttribute{
			Description: "OAuth2 ID token lifespan (e.g., '1h'). Requires Hydra service.",
			Optional:    true,
		},
		"oauth2_id_token_lifespan": schema.StringAttribute{
			Description:        "OAuth2 ID token lifespan (e.g., '1h'). Requires Hydra service.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_ttl_id_token instead. This attribute will be removed in a future major version.",
		},
		"oauth2_ttl_login_consent_request": schema.StringAttribute{
			Description: "OAuth2 login/consent request lifespan (e.g., '30m'). Requires Hydra service.",
			Optional:    true,
		},
		"oauth2_login_consent_request_lifespan": schema.StringAttribute{
			Description:        "OAuth2 login/consent request lifespan (e.g., '30m'). Requires Hydra service.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_ttl_login_consent_request instead. This attribute will be removed in a future major version.",
		},
		"oauth2_mirror_top_level_claims": schema.BoolAttribute{
			Description: "Mirror top-level claims in OAuth2 ID tokens.",
			Optional:    true,
		},
		"oauth2_pkce_enforced": schema.BoolAttribute{
			Description: "Enforce PKCE for all OAuth2 clients.",
			Optional:    true,
		},
		"oauth2_pkce_enforced_for_public_clients": schema.BoolAttribute{
			Description: "Enforce PKCE for public OAuth2 clients only.",
			Optional:    true,
		},
		"oauth2_session_encrypt_at_rest": schema.BoolAttribute{
			Description: "Encrypt OAuth2 sessions at rest.",
			Optional:    true,
		},
		"oauth2_serve_cookies_same_site_legacy_workaround": schema.BoolAttribute{
			Description: "Enable the SameSite=None legacy workaround for OAuth2 cookies. When enabled, a fallback cookie without SameSite is set alongside the main cookie for clients that don't support SameSite=None.",
			Optional:    true,
		},
		"oauth2_cookies_same_site_legacy_workaround": schema.BoolAttribute{
			Description:        "Enable the SameSite=None legacy workaround for OAuth2 cookies. When enabled, a fallback cookie without SameSite is set alongside the main cookie for clients that don't support SameSite=None.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_serve_cookies_same_site_legacy_workaround instead. This attribute will be removed in a future major version.",
		},
		"oauth2_strategies_access_token": schema.StringAttribute{
			Description: "OAuth2 access token strategy ('jwt' or 'opaque').",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf("jwt", "opaque"),
			},
		},
		"oauth2_access_token_strategy": schema.StringAttribute{
			Description:        "OAuth2 access token strategy ('jwt' or 'opaque').",
			Optional:           true,
			DeprecationMessage: "Use oauth2_strategies_access_token instead. This attribute will be removed in a future major version.",
		},
		"oauth2_strategies_jwt_scope_claim": schema.StringAttribute{
			Description: "How scopes are represented in JWT access tokens ('list', 'string', or 'both').",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf("list", "string", "both"),
			},
		},
		"oauth2_jwt_scope_claim": schema.StringAttribute{
			Description:        "How scopes are represented in JWT access tokens ('list', 'string', or 'both').",
			Optional:           true,
			DeprecationMessage: "Use oauth2_strategies_jwt_scope_claim instead. This attribute will be removed in a future major version.",
		},
		"oauth2_strategies_scope": schema.StringAttribute{
			Description: "OAuth2 scope matching strategy ('exact', 'wildcard').",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf("exact", "wildcard", "DEPRECATED_HIERARCHICAL_SCOPE_STRATEGY"),
			},
		},
		"oauth2_scope_strategy": schema.StringAttribute{
			Description:        "OAuth2 scope matching strategy ('exact', 'wildcard').",
			Optional:           true,
			DeprecationMessage: "Use oauth2_strategies_scope instead. This attribute will be removed in a future major version.",
		},
		"oauth2_urls_consent": schema.StringAttribute{
			Description: "OAuth2 consent endpoint URL.",
			Optional:    true,
		},
		"oauth2_consent_url": schema.StringAttribute{
			Description:        "OAuth2 consent endpoint URL.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_urls_consent instead. This attribute will be removed in a future major version.",
		},
		"oauth2_urls_login": schema.StringAttribute{
			Description: "OAuth2 login endpoint URL.",
			Optional:    true,
		},
		"oauth2_login_url": schema.StringAttribute{
			Description:        "OAuth2 login endpoint URL.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_urls_login instead. This attribute will be removed in a future major version.",
		},
		"oauth2_urls_logout": schema.StringAttribute{
			Description: "OAuth2 logout endpoint URL.",
			Optional:    true,
		},
		"oauth2_logout_url": schema.StringAttribute{
			Description:        "OAuth2 logout endpoint URL.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_urls_logout instead. This attribute will be removed in a future major version.",
		},
		"oauth2_urls_error": schema.StringAttribute{
			Description: "OAuth2 error endpoint URL.",
			Optional:    true,
		},
		"oauth2_error_url": schema.StringAttribute{
			Description:        "OAuth2 error endpoint URL.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_urls_error instead. This attribute will be removed in a future major version.",
		},
		"oauth2_urls_self_issuer": schema.StringAttribute{
			Description: "OAuth2 issuer URL. Overrides the default project URL used as the OAuth2/OIDC issuer.",
			Optional:    true,
		},
		"oauth2_issuer_url": schema.StringAttribute{
			Description:        "OAuth2 issuer URL. Overrides the default project URL used as the OAuth2/OIDC issuer.",
			Optional:           true,
			DeprecationMessage: "Use oauth2_urls_self_issuer instead. This attribute will be removed in a future major version.",
		},
		"oauth2_serve_cookies_same_site_mode": schema.StringAttribute{
			Description: "SameSite attribute for OAuth2 cookies ('Lax', 'Strict', 'None').",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf("Lax", "Strict", "None"),
			},
		},
		"oauth2_cookies_same_site_mode": schema.StringAttribute{
			Description:        "SameSite attribute for OAuth2 cookies ('Lax', 'Strict', 'None').",
			Optional:           true,
			DeprecationMessage: "Use oauth2_serve_cookies_same_site_mode instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_login_ui_url": schema.StringAttribute{
			Description: "URL for the login UI.",
			Optional:    true,
		},
		"login_ui_url": schema.StringAttribute{
			Description:        "URL for the login UI.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_login_ui_url instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_registration_ui_url": schema.StringAttribute{
			Description: "URL for the registration UI.",
			Optional:    true,
		},
		"registration_ui_url": schema.StringAttribute{
			Description:        "URL for the registration UI.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_registration_ui_url instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_recovery_ui_url": schema.StringAttribute{
			Description: "URL for the password recovery UI.",
			Optional:    true,
		},
		"recovery_ui_url": schema.StringAttribute{
			Description:        "URL for the password recovery UI.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_recovery_ui_url instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_verification_ui_url": schema.StringAttribute{
			Description: "URL for the verification UI.",
			Optional:    true,
		},
		"verification_ui_url": schema.StringAttribute{
			Description:        "URL for the verification UI.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_verification_ui_url instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_settings_ui_url": schema.StringAttribute{
			Description: "URL for the account settings UI.",
			Optional:    true,
		},
		"settings_ui_url": schema.StringAttribute{
			Description:        "URL for the account settings UI.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_settings_ui_url instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_error_ui_url": schema.StringAttribute{
			Description: "URL for the error UI.",
			Optional:    true,
		},
		"error_ui_url": schema.StringAttribute{
			Description:        "URL for the error UI.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_error_ui_url instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_password_enabled": schema.BoolAttribute{
			Description: "Enable password authentication.",
			Optional:    true,
		},
		"enable_password": schema.BoolAttribute{
			Description:        "Enable password authentication.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_password_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_code_enabled": schema.BoolAttribute{
			Description: "Enable code-based authentication.",
			Optional:    true,
		},
		"enable_code": schema.BoolAttribute{
			Description:        "Enable code-based authentication.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_code_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_code_mfa_enabled": schema.BoolAttribute{
			Description: "Enable the code method as a second factor for MFA. When enabled, users can use one-time codes as a second authentication factor.",
			Optional:    true,
		},
		"code_mfa_enabled": schema.BoolAttribute{
			Description:        "Enable the code method as a second factor for MFA. When enabled, users can use one-time codes as a second authentication factor.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_code_mfa_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_oidc_enabled": schema.BoolAttribute{
			Description: "Enable OIDC (OpenID Connect) social sign-in. Must be enabled for social providers (e.g. Google, GitHub) to work.",
			Optional:    true,
		},
		"enable_oidc": schema.BoolAttribute{
			Description:        "Enable OIDC (OpenID Connect) social sign-in. Must be enabled for social providers (e.g. Google, GitHub) to work.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_oidc_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_oidc_enable_auto_link_policy": schema.BoolAttribute{
			Description: "Enable the OIDC auto-link policy. When true, social sign-in providers with auto_link enabled (on ory_social_provider) can automatically link to existing identities that share the same identifier (e.g., email).",
			Optional:    true,
		},
		"enable_oidc_auto_link_policy": schema.BoolAttribute{
			Description:        "Enable the OIDC auto-link policy. When true, social sign-in providers with auto_link enabled (on ory_social_provider) can automatically link to existing identities that share the same identifier (e.g., email).",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_oidc_enable_auto_link_policy instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_totp_enabled": schema.BoolAttribute{
			Description: "Enable TOTP (Time-based One-Time Password).",
			Optional:    true,
		},
		"enable_totp": schema.BoolAttribute{
			Description:        "Enable TOTP (Time-based One-Time Password).",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_totp_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_webauthn_enabled": schema.BoolAttribute{
			Description: "Enable WebAuthn (hardware keys).",
			Optional:    true,
		},
		"enable_webauthn": schema.BoolAttribute{
			Description:        "Enable WebAuthn (hardware keys).",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_webauthn_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_passkey_enabled": schema.BoolAttribute{
			Description: "Enable Passkey authentication.",
			Optional:    true,
		},
		"enable_passkey": schema.BoolAttribute{
			Description:        "Enable Passkey authentication.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_passkey_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_lookup_secret_enabled": schema.BoolAttribute{
			Description: "Enable backup/recovery codes.",
			Optional:    true,
		},
		"enable_lookup_secret": schema.BoolAttribute{
			Description:        "Enable backup/recovery codes.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_lookup_secret_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_profile_enabled": schema.BoolAttribute{
			Description: "Enable the profile authentication method. When enabled, users can update their identity traits (e.g., name, address) via the settings flow.",
			Optional:    true,
		},
		"enable_profile": schema.BoolAttribute{
			Description:        "Enable the profile authentication method. When enabled, users can update their identity traits (e.g., name, address) via the settings flow.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_profile_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_code_config_lifespan": schema.StringAttribute{
			Description: "Lifespan of the code method's one-time codes (e.g., '15m0s'). Controls how long a code remains valid after being issued.",
			Optional:    true,
		},
		"code_lifespan": schema.StringAttribute{
			Description:        "Lifespan of the code method's one-time codes (e.g., '15m0s'). Controls how long a code remains valid after being issued.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_code_config_lifespan instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_code_config_missing_credential_fallback_enabled": schema.BoolAttribute{
			Description: "Enable missing credential fallback for the code method. When enabled, allows the code method to be used as a fallback when the primary credential is missing.",
			Optional:    true,
		},
		"code_missing_credential_fallback_enabled": schema.BoolAttribute{
			Description:        "Enable missing credential fallback for the code method. When enabled, allows the code method to be used as a fallback when the primary credential is missing.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_code_config_missing_credential_fallback_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_password_config_min_password_length": schema.Int64Attribute{
			Description: "Minimum password length.",
			Optional:    true,
		},
		"password_min_length": schema.Int64Attribute{
			Description:        "Minimum password length.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_password_config_min_password_length instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_password_config_haveibeenpwned_enabled": schema.BoolAttribute{
			Description: "Check passwords against HaveIBeenPwned.",
			Optional:    true,
		},
		"password_check_haveibeenpwned": schema.BoolAttribute{
			Description:        "Check passwords against HaveIBeenPwned.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_password_config_haveibeenpwned_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_password_config_max_breaches": schema.Int64Attribute{
			Description: "Maximum allowed breaches in HaveIBeenPwned.",
			Optional:    true,
		},
		"password_max_breaches": schema.Int64Attribute{
			Description:        "Maximum allowed breaches in HaveIBeenPwned.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_password_config_max_breaches instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_password_config_identifier_similarity_check_enabled": schema.BoolAttribute{
			Description: "Check password similarity to identifier.",
			Optional:    true,
		},
		"password_identifier_similarity": schema.BoolAttribute{
			Description:        "Check password similarity to identifier.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_password_config_identifier_similarity_check_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_recovery_enabled": schema.BoolAttribute{
			Description: "Enable password recovery flow.",
			Optional:    true,
		},
		"enable_recovery": schema.BoolAttribute{
			Description:        "Enable password recovery flow.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_recovery_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_verification_enabled": schema.BoolAttribute{
			Description: "Enable email verification flow.",
			Optional:    true,
		},
		"enable_verification": schema.BoolAttribute{
			Description:        "Enable email verification flow.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_verification_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_registration_enabled": schema.BoolAttribute{
			Description: "Enable user registration.",
			Optional:    true,
		},
		"enable_registration": schema.BoolAttribute{
			Description:        "Enable user registration.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_registration_enabled instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_login_style": schema.StringAttribute{
			Description: "Login flow style: 'unified' (default) shows all auth methods on one screen, 'identifier_first' collects the identifier before showing auth methods.",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf("unified", "identifier_first"),
			},
		},
		"login_style": schema.StringAttribute{
			Description:        "Login flow style: 'unified' (default) shows all auth methods on one screen, 'identifier_first' collects the identifier before showing auth methods.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_login_style instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_settings_lifespan": schema.StringAttribute{
			Description: "Lifespan of the settings flow (e.g., '30m0s'). Controls how long a settings flow session remains valid.",
			Optional:    true,
		},
		"settings_lifespan": schema.StringAttribute{
			Description:        "Lifespan of the settings flow (e.g., '30m0s'). Controls how long a settings flow session remains valid.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_settings_lifespan instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_settings_privileged_session_max_age": schema.StringAttribute{
			Description: "Maximum age of a privileged session for the settings flow (e.g., '15m0s'). After this duration, the user must re-authenticate to make privileged changes like password updates.",
			Optional:    true,
		},
		"settings_privileged_session_max_age": schema.StringAttribute{
			Description:        "Maximum age of a privileged session for the settings flow (e.g., '15m0s'). After this duration, the user must re-authenticate to make privileged changes like password updates.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_settings_privileged_session_max_age instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_settings_required_aal": schema.StringAttribute{
			Description: "Required Authenticator Assurance Level for the settings flow: 'aal1' or 'highest_available'.",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf("aal1", "highest_available"),
			},
		},
		"required_aal": schema.StringAttribute{
			Description:        "Required Authenticator Assurance Level for the settings flow: 'aal1' or 'highest_available'.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_settings_required_aal instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_verification_use": schema.StringAttribute{
			Description: "Verification method to use: 'code' (one-time code) or 'link' (magic link).",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf("code", "link"),
			},
		},
		"verification_use": schema.StringAttribute{
			Description:        "Verification method to use: 'code' (one-time code) or 'link' (magic link).",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_verification_use instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_verification_lifespan": schema.StringAttribute{
			Description: "Lifespan of the verification flow (e.g., '30m0s'). Controls how long a verification flow session remains valid.",
			Optional:    true,
		},
		"verification_lifespan": schema.StringAttribute{
			Description:        "Lifespan of the verification flow (e.g., '30m0s'). Controls how long a verification flow session remains valid.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_verification_lifespan instead. This attribute will be removed in a future major version.",
		},
		"selfservice_flows_verification_notify_unknown_recipients": schema.BoolAttribute{
			Description: "When enabled, verification emails are sent even if the email address is not associated with any known identity.",
			Optional:    true,
		},
		"verification_notify_unknown_recipients": schema.BoolAttribute{
			Description:        "When enabled, verification emails are sent even if the email address is not associated with any known identity.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_flows_verification_notify_unknown_recipients instead. This attribute will be removed in a future major version.",
		},
		"courier_smtp_from_address": schema.StringAttribute{
			Description: "Email address to send from.",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.RegexMatches(
					regexp.MustCompile("^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$"),
					"must be a valid email address",
				),
			},
		},
		"smtp_from_address": schema.StringAttribute{
			Description:        "Email address to send from.",
			Optional:           true,
			DeprecationMessage: "Use courier_smtp_from_address instead. This attribute will be removed in a future major version.",
		},
		"courier_smtp_from_name": schema.StringAttribute{
			Description: "Name to display as sender.",
			Optional:    true,
		},
		"smtp_from_name": schema.StringAttribute{
			Description:        "Name to display as sender.",
			Optional:           true,
			DeprecationMessage: "Use courier_smtp_from_name instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_totp_config_issuer": schema.StringAttribute{
			Description: "TOTP issuer name shown in authenticator apps.",
			Optional:    true,
		},
		"totp_issuer": schema.StringAttribute{
			Description:        "TOTP issuer name shown in authenticator apps.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_totp_config_issuer instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_webauthn_config_rp_display_name": schema.StringAttribute{
			Description: "WebAuthn Relying Party display name.",
			Optional:    true,
		},
		"webauthn_rp_display_name": schema.StringAttribute{
			Description:        "WebAuthn Relying Party display name.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_webauthn_config_rp_display_name instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_webauthn_config_rp_id": schema.StringAttribute{
			Description: "WebAuthn Relying Party ID (typically your domain).",
			Optional:    true,
		},
		"webauthn_rp_id": schema.StringAttribute{
			Description:        "WebAuthn Relying Party ID (typically your domain).",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_webauthn_config_rp_id instead. This attribute will be removed in a future major version.",
		},
		"selfservice_methods_webauthn_config_passwordless": schema.BoolAttribute{
			Description: "Enable passwordless WebAuthn authentication.",
			Optional:    true,
		},
		"webauthn_passwordless": schema.BoolAttribute{
			Description:        "Enable passwordless WebAuthn authentication.",
			Optional:           true,
			DeprecationMessage: "Use selfservice_methods_webauthn_config_passwordless instead. This attribute will be removed in a future major version.",
		},
		"courier_delivery_strategy": schema.StringAttribute{
			Description: "Courier delivery strategy: 'smtp' (default) or 'http'.",
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.OneOf("smtp", "http"),
			},
		},
		"account_experience_favicon_url": schema.StringAttribute{
			Description: "URL for the favicon in the hosted login UI.",
			Optional:    true,
		},
		"account_experience_logo_url": schema.StringAttribute{
			Description: "URL for the logo in the hosted login UI.",
			Optional:    true,
		},
		"account_experience_name": schema.StringAttribute{
			Description: "Application name shown in the hosted login UI.",
			Optional:    true,
		},
		"account_experience_stylesheet": schema.StringAttribute{
			Description: "Custom CSS stylesheet for the hosted login UI.",
			Optional:    true,
		},
		"account_experience_default_locale": schema.StringAttribute{
			Description: "Default locale for the hosted login UI (e.g., 'en', 'de').",
			Optional:    true,
		},
		"oauth2_client_credentials_default_grant_allowed_scope": schema.BoolAttribute{
			Description: "Automatically grant the full authorized scope in OAuth2 client credentials flow.",
			Optional:    true,
		},
		"oauth2_exclude_not_before_claim": schema.BoolAttribute{
			Description: "Exclude the `nbf` (not before) claim from access tokens.",
			Optional:    true,
		},
		"oauth2_grant_jwt_iat_optional": schema.BoolAttribute{
			Description: "Make the `iat` claim optional in JWT assertion grants (RFC 7523).",
			Optional:    true,
		},
		"oauth2_grant_jwt_jti_optional": schema.BoolAttribute{
			Description: "Make the `jti` claim optional in JWT assertion grants (RFC 7523).",
			Optional:    true,
		},
		"oauth2_grant_jwt_max_ttl": schema.StringAttribute{
			Description: "Maximum TTL for JWT assertions in grant flows (e.g. '720h').",
			Optional:    true,
		},
		"oauth2_grant_refresh_token_rotation_grace_period": schema.StringAttribute{
			Description: "Grace period for refresh token rotation (e.g. '5s'). Set to '0s' to disable.",
			Optional:    true,
		},
		"oauth2_refresh_token_hook": schema.StringAttribute{
			Description: "Webhook URL called during OAuth2 token refresh to update access token claims.",
			Optional:    true,
		},
		"oauth2_token_hook": schema.StringAttribute{
			Description: "Webhook URL called during token issuance for all grant types to customize claims.",
			Optional:    true,
		},
		"oidc_dynamic_client_registration_enabled": schema.BoolAttribute{
			Description: "Enable OpenID Connect dynamic client registration.",
			Optional:    true,
		},
		"oidc_subject_identifiers_pairwise_salt": schema.StringAttribute{
			Description: "Salt for the OIDC pairwise subject identifier algorithm.",
			Optional:    true,
		},
		"oauth2_urls_post_logout_redirect": schema.StringAttribute{
			Description: "Default redirect URL after OAuth2 logout.",
			Optional:    true,
		},
		"oauth2_urls_registration": schema.StringAttribute{
			Description: "Registration endpoint URL for the OAuth2 login and consent flow.",
			Optional:    true,
		},
		"oauth2_webfinger_oidc_discovery_auth_url": schema.StringAttribute{
			Description: "Override the OAuth2 authorization URL in OIDC discovery.",
			Optional:    true,
		},
		"oauth2_webfinger_oidc_discovery_client_registration_url": schema.StringAttribute{
			Description: "Override the dynamic client registration URL in OIDC discovery.",
			Optional:    true,
		},
		"oauth2_webfinger_oidc_discovery_jwks_url": schema.StringAttribute{
			Description: "Override the JWKS URL in OIDC discovery.",
			Optional:    true,
		},
		"oauth2_webfinger_oidc_discovery_token_url": schema.StringAttribute{
			Description: "Override the OAuth2 token URL in OIDC discovery.",
			Optional:    true,
		},
		"oauth2_webfinger_oidc_discovery_userinfo_url": schema.StringAttribute{
			Description: "Override the userinfo endpoint URL in OIDC discovery.",
			Optional:    true,
		},
		"cookies_same_site": schema.StringAttribute{
			Description: "SameSite attribute for identity service cookies.",
			Optional:    true,
		},
		"courier_http_request_config_auth_api_key_in": schema.StringAttribute{
			Description: "Where to send the API key for HTTP courier auth ('header' or 'cookie').",
			Optional:    true,
		},
		"courier_http_request_config_auth_api_key_name": schema.StringAttribute{
			Description: "API key name for HTTP courier authentication.",
			Optional:    true,
		},
		"courier_http_request_config_auth_api_key_value": schema.StringAttribute{
			Description: "API key value for HTTP courier authentication.",
			Optional:    true,
			Sensitive:   true,
		},
		"courier_http_request_config_auth_basic_auth_password": schema.StringAttribute{
			Description: "Password for HTTP courier basic authentication.",
			Optional:    true,
			Sensitive:   true,
		},
		"courier_http_request_config_auth_basic_auth_user": schema.StringAttribute{
			Description: "Username for HTTP courier basic authentication.",
			Optional:    true,
		},
		"courier_http_request_config_body": schema.StringAttribute{
			Description: "Base64-encoded Jsonnet template for the HTTP courier request body.",
			Optional:    true,
		},
		"courier_http_request_config_url": schema.StringAttribute{
			Description: "URL of the remote HTTP email sending service.",
			Optional:    true,
		},
		"courier_smtp_local_name": schema.StringAttribute{
			Description: "Local hostname used in SMTP HELO/EHLO commands.",
			Optional:    true,
		},
		"courier_templates_login_code_valid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for valid login-by-code emails.",
			Optional:    true,
		},
		"courier_templates_login_code_valid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for valid login-by-code emails.",
			Optional:    true,
		},
		"courier_templates_login_code_valid_email_subject": schema.StringAttribute{
			Description: "Subject template for valid login-by-code emails.",
			Optional:    true,
		},
		"courier_templates_login_code_valid_sms_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for valid login-by-code SMS messages.",
			Optional:    true,
		},
		"courier_templates_recovery_code_invalid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for invalid recovery-by-code emails.",
			Optional:    true,
		},
		"courier_templates_recovery_code_invalid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for invalid recovery-by-code emails.",
			Optional:    true,
		},
		"courier_templates_recovery_code_invalid_email_subject": schema.StringAttribute{
			Description: "Subject template for invalid recovery-by-code emails.",
			Optional:    true,
		},
		"courier_templates_recovery_code_valid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for valid recovery-by-code emails.",
			Optional:    true,
		},
		"courier_templates_recovery_code_valid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for valid recovery-by-code emails.",
			Optional:    true,
		},
		"courier_templates_recovery_code_valid_email_subject": schema.StringAttribute{
			Description: "Subject template for valid recovery-by-code emails.",
			Optional:    true,
		},
		"courier_templates_recovery_invalid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for invalid recovery emails.",
			Optional:    true,
		},
		"courier_templates_recovery_invalid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for invalid recovery emails.",
			Optional:    true,
		},
		"courier_templates_recovery_invalid_email_subject": schema.StringAttribute{
			Description: "Subject template for invalid recovery emails.",
			Optional:    true,
		},
		"courier_templates_recovery_valid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for valid recovery emails.",
			Optional:    true,
		},
		"courier_templates_recovery_valid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for valid recovery emails.",
			Optional:    true,
		},
		"courier_templates_recovery_valid_email_subject": schema.StringAttribute{
			Description: "Subject template for valid recovery emails.",
			Optional:    true,
		},
		"courier_templates_registration_code_valid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for valid registration-by-code emails.",
			Optional:    true,
		},
		"courier_templates_registration_code_valid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for valid registration-by-code emails.",
			Optional:    true,
		},
		"courier_templates_registration_code_valid_email_subject": schema.StringAttribute{
			Description: "Subject template for valid registration-by-code emails.",
			Optional:    true,
		},
		"courier_templates_registration_code_valid_sms_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for valid registration-by-code SMS messages.",
			Optional:    true,
		},
		"courier_templates_verification_code_invalid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for invalid verification-by-code emails.",
			Optional:    true,
		},
		"courier_templates_verification_code_invalid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for invalid verification-by-code emails.",
			Optional:    true,
		},
		"courier_templates_verification_code_invalid_email_subject": schema.StringAttribute{
			Description: "Subject template for invalid verification-by-code emails.",
			Optional:    true,
		},
		"courier_templates_verification_code_valid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for valid verification-by-code emails.",
			Optional:    true,
		},
		"courier_templates_verification_code_valid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for valid verification-by-code emails.",
			Optional:    true,
		},
		"courier_templates_verification_code_valid_email_subject": schema.StringAttribute{
			Description: "Subject template for valid verification-by-code emails.",
			Optional:    true,
		},
		"courier_templates_verification_code_valid_sms_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for valid verification-by-code SMS messages.",
			Optional:    true,
		},
		"courier_templates_verification_invalid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for invalid verification emails.",
			Optional:    true,
		},
		"courier_templates_verification_invalid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for invalid verification emails.",
			Optional:    true,
		},
		"courier_templates_verification_invalid_email_subject": schema.StringAttribute{
			Description: "Subject template for invalid verification emails.",
			Optional:    true,
		},
		"courier_templates_verification_valid_email_body_html": schema.StringAttribute{
			Description: "HTML body template for valid verification emails.",
			Optional:    true,
		},
		"courier_templates_verification_valid_email_body_plaintext": schema.StringAttribute{
			Description: "Plaintext body template for valid verification emails.",
			Optional:    true,
		},
		"courier_templates_verification_valid_email_subject": schema.StringAttribute{
			Description: "Subject template for valid verification emails.",
			Optional:    true,
		},
		"feature_flags_cacheable_sessions": schema.BoolAttribute{
			Description: "Enable session caching.",
			Optional:    true,
		},
		"feature_flags_cacheable_sessions_max_age": schema.StringAttribute{
			Description: "Maximum age for cached sessions (e.g. '5m').",
			Optional:    true,
		},
		"feature_flags_choose_recovery_address": schema.BoolAttribute{
			Description: "Allow users to choose which recovery address to use.",
			Optional:    true,
		},
		"feature_flags_faster_session_extend": schema.BoolAttribute{
			Description: "Enable faster session extension by skipping the session lookup.",
			Optional:    true,
		},
		"feature_flags_legacy_continue_with_verification_ui": schema.BoolAttribute{
			Description: "Deprecated. Restore legacy behavior of always including show_verification_ui in continue_with.",
			Optional:    true,
		},
		"feature_flags_legacy_oidc_registration_node_group": schema.BoolAttribute{
			Description: "Use legacy 'oidc' node group for OIDC registration when required fields are missing.",
			Optional:    true,
		},
		"feature_flags_legacy_require_verified_login_error": schema.BoolAttribute{
			Description: "Deprecated. Return a form error instead of continue_with when the login identifier is not verified.",
			Optional:    true,
		},
		"feature_flags_use_continue_with_transitions": schema.BoolAttribute{
			Description: "Enable continue_with transitions for session flows.",
			Optional:    true,
		},
		"oauth2_provider_url": schema.StringAttribute{
			Description: "OAuth2 provider integration URL.",
			Optional:    true,
		},
		"selfservice_default_browser_return_url": schema.StringAttribute{
			Description: "Default browser return URL for self-service flows.",
			Optional:    true,
		},
		"selfservice_flows_login_after_code_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after login via code method.",
			Optional:    true,
		},
		"selfservice_flows_login_after_default_browser_return_url": schema.StringAttribute{
			Description: "Default return URL after login.",
			Optional:    true,
		},
		"selfservice_flows_login_after_lookup_secret_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after login via lookup secret method.",
			Optional:    true,
		},
		"selfservice_flows_login_after_oidc_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after login via OIDC.",
			Optional:    true,
		},
		"selfservice_flows_login_after_passkey_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after login via passkey.",
			Optional:    true,
		},
		"selfservice_flows_login_after_password_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after login via password.",
			Optional:    true,
		},
		"selfservice_flows_login_after_totp_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after login via TOTP.",
			Optional:    true,
		},
		"selfservice_flows_login_after_webauthn_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after login via WebAuthn.",
			Optional:    true,
		},
		"selfservice_flows_login_lifespan": schema.StringAttribute{
			Description: "Lifespan of the login flow (e.g. '1h').",
			Optional:    true,
		},
		"selfservice_flows_logout_after_default_browser_return_url": schema.StringAttribute{
			Description: "Default return URL after logout.",
			Optional:    true,
		},
		"selfservice_flows_recovery_after_default_browser_return_url": schema.StringAttribute{
			Description: "Default return URL after recovery.",
			Optional:    true,
		},
		"selfservice_flows_recovery_lifespan": schema.StringAttribute{
			Description: "Lifespan of the recovery flow (e.g. '1h').",
			Optional:    true,
		},
		"selfservice_flows_recovery_notify_unknown_recipients": schema.BoolAttribute{
			Description: "Send recovery notifications even when the email is not registered.",
			Optional:    true,
		},
		"selfservice_flows_recovery_use": schema.StringAttribute{
			Description: "Recovery strategy to use ('link' or 'code').",
			Optional:    true,
		},
		"selfservice_flows_registration_after_code_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after registration via code method.",
			Optional:    true,
		},
		"selfservice_flows_registration_after_default_browser_return_url": schema.StringAttribute{
			Description: "Default return URL after registration.",
			Optional:    true,
		},
		"selfservice_flows_registration_after_oidc_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after registration via OIDC.",
			Optional:    true,
		},
		"selfservice_flows_registration_after_passkey_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after registration via passkey.",
			Optional:    true,
		},
		"selfservice_flows_registration_after_password_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after registration via password.",
			Optional:    true,
		},
		"selfservice_flows_registration_after_webauthn_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after registration via WebAuthn.",
			Optional:    true,
		},
		"selfservice_flows_registration_enable_legacy_one_step": schema.BoolAttribute{
			Description: "Revert to legacy one-step registration instead of the two-step flow.",
			Optional:    true,
		},
		"selfservice_flows_registration_lifespan": schema.StringAttribute{
			Description: "Lifespan of the registration flow (e.g. '1h').",
			Optional:    true,
		},
		"selfservice_flows_registration_login_hints": schema.BoolAttribute{
			Description: "Show login hints when a user tries to register with a duplicate account.",
			Optional:    true,
		},
		"selfservice_flows_settings_after_default_browser_return_url": schema.StringAttribute{
			Description: "Default return URL after updating settings.",
			Optional:    true,
		},
		"selfservice_flows_settings_after_lookup_secret_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after updating lookup secrets in settings.",
			Optional:    true,
		},
		"selfservice_flows_settings_after_oidc_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after updating OIDC connections in settings.",
			Optional:    true,
		},
		"selfservice_flows_settings_after_passkey_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after updating passkey in settings.",
			Optional:    true,
		},
		"selfservice_flows_settings_after_password_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after updating password in settings.",
			Optional:    true,
		},
		"selfservice_flows_settings_after_profile_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after updating profile in settings.",
			Optional:    true,
		},
		"selfservice_flows_settings_after_totp_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after updating TOTP in settings.",
			Optional:    true,
		},
		"selfservice_flows_settings_after_webauthn_default_browser_return_url": schema.StringAttribute{
			Description: "Return URL after updating WebAuthn in settings.",
			Optional:    true,
		},
		"selfservice_flows_verification_after_default_browser_return_url": schema.StringAttribute{
			Description: "Default return URL after verification.",
			Optional:    true,
		},
		"selfservice_methods_code_passwordless_enabled": schema.BoolAttribute{
			Description: "Enable passwordless login via the code method.",
			Optional:    true,
		},
		"selfservice_methods_code_passwordless_login_fallback_enabled": schema.BoolAttribute{
			Description: "Allow code-based login as a fallback for users registered with other methods.",
			Optional:    true,
		},
		"selfservice_methods_link_config_base_url": schema.StringAttribute{
			Description: "Base URL for recovery, verification, and login links. Leave empty for automatic detection.",
			Optional:    true,
		},
		"selfservice_methods_link_config_lifespan": schema.StringAttribute{
			Description: "Lifespan of magic links (e.g. '1h').",
			Optional:    true,
		},
		"selfservice_methods_link_enabled": schema.BoolAttribute{
			Description: "Enable the magic link authentication method.",
			Optional:    true,
		},
		"selfservice_methods_oidc_config_base_redirect_uri": schema.StringAttribute{
			Description: "Base redirect URI for OIDC/social sign-in callbacks.",
			Optional:    true,
		},
		"selfservice_methods_passkey_config_rp_display_name": schema.StringAttribute{
			Description: "Passkey relying party display name.",
			Optional:    true,
		},
		"selfservice_methods_passkey_config_rp_id": schema.StringAttribute{
			Description: "Passkey relying party ID (typically your domain).",
			Optional:    true,
		},
		"selfservice_methods_password_config_ignore_network_errors": schema.BoolAttribute{
			Description: "Ignore HaveIBeenPwned network errors during password validation.",
			Optional:    true,
		},
		"selfservice_methods_saml_enabled": schema.BoolAttribute{
			Description: "Enable SAML login method.",
			Optional:    true,
		},
		"selfservice_methods_webauthn_config_rp_icon": schema.StringAttribute{
			Description: "Deprecated. WebAuthn relying party icon URL (ignored for security reasons).",
			Optional:    true,
		},
		"account_experience_enabled_locales": schema.ListAttribute{
			Description: "Enabled locales for the hosted login UI.",
			Optional:    true,
			ElementType: types.StringType,
		},
		"account_experience_favicon_dark": schema.StringAttribute{
			Description: "URL for the dark theme favicon in the hosted login UI.",
			Optional:    true,
		},
		"account_experience_favicon_light": schema.StringAttribute{
			Description: "URL for the light theme favicon in the hosted login UI.",
			Optional:    true,
		},
		"account_experience_locale_behavior": schema.StringAttribute{
			Description: "Locale behavior: 'respect_accept_language' or 'force_default'.",
			Optional:    true,
		},
		"account_experience_logo_dark": schema.StringAttribute{
			Description: "URL for the dark theme logo in the hosted login UI.",
			Optional:    true,
		},
		"account_experience_logo_light": schema.StringAttribute{
			Description: "URL for the light theme logo in the hosted login UI.",
			Optional:    true,
		},
		"account_experience_theme_variables_dark": schema.StringAttribute{
			Description: "URL for dark theme CSS variables in the hosted login UI.",
			Optional:    true,
		},
		"account_experience_theme_variables_light": schema.StringAttribute{
			Description: "URL for light theme CSS variables in the hosted login UI.",
			Optional:    true,
		},
		"disable_account_experience_welcome_screen": schema.BoolAttribute{
			Description: "Disable the account experience welcome screen at /ui/welcome.",
			Optional:    true,
		},
		"enable_ax_v2": schema.BoolAttribute{
			Description: "Enable the new account experience UI.",
			Optional:    true,
		},
		"oidc_dynamic_client_registration_default_scope": schema.ListAttribute{
			Description: "Default OAuth2 scopes granted to dynamically registered clients.",
			Optional:    true,
			ElementType: types.StringType,
		},
		"oidc_subject_identifiers_supported_types": schema.ListAttribute{
			Description: "Supported OIDC subject identifier types ('public', 'pairwise').",
			Optional:    true,
			ElementType: types.StringType,
		},
		"oauth2_secrets_cookie": schema.ListAttribute{
			Description: "Cookie signing secrets for the OAuth2 service.",
			Optional:    true,
			ElementType: types.StringType,
			Sensitive:   true,
		},
		"oauth2_secrets_pagination": schema.ListAttribute{
			Description: "Pagination encryption keys for the OAuth2 service.",
			Optional:    true,
			ElementType: types.StringType,
			Sensitive:   true,
		},
		"oauth2_secrets_system": schema.ListAttribute{
			Description: "System-wide encryption secrets for the OAuth2 service.",
			Optional:    true,
			ElementType: types.StringType,
			Sensitive:   true,
		},
		"oauth2_webfinger_jwks_broadcast_keys": schema.ListAttribute{
			Description: "JWK set IDs to broadcast via OIDC discovery.",
			Optional:    true,
			ElementType: types.StringType,
		},
		"oauth2_webfinger_oidc_discovery_supported_claims": schema.ListAttribute{
			Description: "Supported claims advertised in OIDC discovery.",
			Optional:    true,
			ElementType: types.StringType,
		},
		"oauth2_webfinger_oidc_discovery_supported_scope": schema.ListAttribute{
			Description: "Supported scopes advertised in OIDC discovery.",
			Optional:    true,
			ElementType: types.StringType,
		},
		"keto_namespace_configuration": schema.StringAttribute{
			Description: "URL pointing to an OPL file with the Keto namespace configuration.",
			Optional:    true,
		},
		"keto_secrets_pagination": schema.ListAttribute{
			Description: "Pagination encryption keys for the permission service.",
			Optional:    true,
			ElementType: types.StringType,
			Sensitive:   true,
		},
		"feature_flags_password_profile_registration_node_group": schema.BoolAttribute{
			Description: "Use password method group for profile registration node group.",
			Optional:    true,
		},
		"oauth2_provider_headers": schema.MapAttribute{
			Description: "Custom HTTP headers for the OAuth2 provider integration.",
			Optional:    true,
			ElementType: types.StringType,
		},
		"oauth2_provider_override_return_to": schema.BoolAttribute{
			Description: "Allow the OAuth2 provider to automatically set the return_to parameter.",
			Optional:    true,
		},
		"preview_default_read_consistency_level": schema.StringAttribute{
			Description: "Default read consistency level for identity APIs ('strong' or 'eventual').",
			Optional:    true,
		},
		"identity_secrets_cipher": schema.ListAttribute{
			Description: "Encryption secrets for identity data at rest.",
			Optional:    true,
			ElementType: types.StringType,
			Sensitive:   true,
		},
		"identity_secrets_cookie": schema.ListAttribute{
			Description: "Cookie signing secrets for the identity service.",
			Optional:    true,
			ElementType: types.StringType,
			Sensitive:   true,
		},
		"identity_secrets_default": schema.ListAttribute{
			Description: "Default signing secrets for the identity service.",
			Optional:    true,
			ElementType: types.StringType,
			Sensitive:   true,
		},
		"identity_secrets_pagination": schema.ListAttribute{
			Description: "Pagination encryption keys for the identity service.",
			Optional:    true,
			ElementType: types.StringType,
			Sensitive:   true,
		},
		"security_account_enumeration_mitigate": schema.BoolAttribute{
			Description: "Mitigate account enumeration when using identifier-first login.",
			Optional:    true,
		},
		"selfservice_methods_captcha_config_allowed_domains": schema.ListAttribute{
			Description: "Domains allowed for CAPTCHA verification.",
			Optional:    true,
			ElementType: types.StringType,
		},
		"selfservice_methods_captcha_config_byo": schema.BoolAttribute{
			Description: "Use bring-your-own CAPTCHA widget instead of managed.",
			Optional:    true,
		},
		"selfservice_methods_captcha_config_cf_turnstile_byo_secret": schema.StringAttribute{
			Description: "Cloudflare Turnstile BYO site secret (private).",
			Optional:    true,
			Sensitive:   true,
		},
		"selfservice_methods_captcha_config_cf_turnstile_byo_sitekey": schema.StringAttribute{
			Description: "Cloudflare Turnstile site key for BYO CAPTCHA.",
			Optional:    true,
		},
		"selfservice_methods_captcha_config_cf_turnstile_secret": schema.StringAttribute{
			Description: "Cloudflare Turnstile managed site secret (private).",
			Optional:    true,
			Sensitive:   true,
		},
		"selfservice_methods_captcha_config_cf_turnstile_sitekey": schema.StringAttribute{
			Description: "Cloudflare Turnstile site key for managed CAPTCHA.",
			Optional:    true,
		},
		"selfservice_methods_captcha_config_legacy_inject_node": schema.BoolAttribute{
			Description: "Inject CAPTCHA as a legacy UI node.",
			Optional:    true,
		},
		"selfservice_methods_captcha_enabled": schema.BoolAttribute{
			Description: "Enable CAPTCHA protection for self-service flows.",
			Optional:    true,
		},
		"selfservice_methods_code_config_max_submissions": schema.Int64Attribute{
			Description: "Maximum number of code submission attempts before invalidation.",
			Optional:    true,
		},
		"selfservice_methods_passkey_config_rp_origins": schema.ListAttribute{
			Description: "Allowed origins for passkey relying party verification.",
			Optional:    true,
			ElementType: types.StringType,
		},
	}
}
