name: Renovate

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_8,11,14,17_*_*_*
    - cron: '0 8,11,14,17 * * *'

permissions:
  contents: read

concurrency:
  group: renovate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@973d3e5a68e735a444e8c03432b66eedb343c302 # v46.2.0
        with:
          configurationFile: 'renovate-self-hosted.json'
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|AWS_TOKEN)$"
          token: '${{ secrets.ORY_BOT_PAT }}'
